"""Postgres-only validation of the Alembic history (APRAS-58, APRAS-66).

The history used to be 39 revision modules; APRAS-58 replaced it with one
autogenerated revision, ``0001_initial_schema``, produced from the final
``SQLModel.metadata``. APRAS-66 added the second, ``0002_tenant_slug``: the
rule that a new column goes *inside* ``0001`` held only while ``0001`` had
never been applied, and production applied it on 2026-09-19 (APRAS-59).
APRAS-71 added the third, ``0003_tenant_invitation``, under the same rule.

So there is a chain again, and it is a **line**: one root, one head, no
branch. This module asserts that shape, that the history at head builds
*exactly* the schema the models describe, that it seeds *exactly* the default
tenant and its six legacy roles, and that it round-trips.

It runs against a real PostgreSQL and never against SQLite, which stores enum
columns as a plain ``VARCHAR``, enforces no native constraint, and would let
a divergence between the migration and the models pass unnoticed. The whole
module self-skips unless ``TEST_POSTGRES_URL`` points at a reachable database
it is allowed to destroy -- every fixture runs ``DROP SCHEMA public
CASCADE``. CI is therefore the source of truth, and
``scripts/assert_no_skips.py`` refuses a run in which the module skipped.

    docker run -d --rm -p 55432:5432 \\
        -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=apras_test \\
        -e POSTGRES_INITDB_ARGS="--encoding=UTF8 --locale=C" \\
        postgres:16-alpine

    TEST_POSTGRES_URL=postgresql://postgres:postgres@localhost:55432/apras_test \\
        SECRET_KEY=test uv run pytest tests/test_migrations_postgres.py -v

The cluster must be UTF-8: the migration seeds ``Condomínio Padrão``.
"""

import ast
import os
import pathlib
import re
import subprocess
import sys
import uuid

import pytest
from sqlalchemy import create_engine, text
from sqlmodel import SQLModel

# Imported for its side effect: registering every mapper, so
# `SQLModel.metadata` is exhaustive when the schema is compared against it.
import app.models  # noqa: F401  # every model must be imported before the metadata is compared
from app.core.tenant_context import TENANT_SCOPED_MODELS
from app.services.tenant_service import LEGACY_ROLE_NAMES

TEST_POSTGRES_URL = os.environ.get("TEST_POSTGRES_URL")
_BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#: The head, and the root, spelled once each: a task that adds a third
#: revision appends to :data:`EXPECTED_HISTORY` and moves
#: :data:`HEAD_REVISION` rather than hunting for literals.
ROOT_REVISION = "0001_initial_schema"
HEAD_REVISION = "0003_tenant_invitation"

#: The whole history, oldest first. ``upgrade head`` replays it in this order
#: and each entry's ``down_revision`` is asserted to be its predecessor, so a
#: branch or an orphan cannot hide behind a green ``upgrade``.
EXPECTED_HISTORY = (ROOT_REVISION, "0002_tenant_slug", HEAD_REVISION)

#: ``alembic_version.version_num`` is ``VARCHAR(32)``: a longer slug fails on
#: the first real ``upgrade``, not at import time, which is how the retired
#: ``0037`` learnt it.
_REVISION_LENGTH_LIMIT = 32

_VERSIONS_DIR = pathlib.Path(_BACKEND_DIR) / "alembic" / "versions"

DEFAULT_TENANT_ID = uuid.UUID("00000000-0000-0000-0000-000000000001")

#: The 3-64 rule of `app/core/slug.py`, restated as literals so this module
#: can assert every backfilled row satisfies it without importing the
#: application half of the pin (APRAS-66 D-E).
_SLUG_RULE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")
_SLUG_BOUNDS = (3, 64)

pytestmark = pytest.mark.skipif(
    not TEST_POSTGRES_URL,
    reason=(
        "TEST_POSTGRES_URL not set; skipping the Postgres-only migration "
        "tests (they need a real Postgres instance they may destroy, e.g. "
        "via Docker). SQLite enforces neither enums nor most constraints."
    ),
)


def _run_alembic(*args: str) -> None:
    """Run the alembic CLI in a subprocess.

    Invoked as the ``alembic`` console-script entry point (rather than
    ``python -m alembic`` or importing ``alembic.command`` in-process)
    because this project's own ``backend/alembic/`` migrations directory is
    itself an importable package (per ``pytest.ini``'s ``pythonpath = .``),
    which shadows the real third-party ``alembic`` library whenever the
    current working directory ends up on ``sys.path[0]`` (as happens both
    for in-process imports and for ``python -m alembic``).
    """
    result = _alembic(*args)
    assert result.returncode == 0, (
        f"alembic {' '.join(args)} failed:\nstdout={result.stdout}\nstderr={result.stderr}"
    )


def _alembic(*args: str) -> subprocess.CompletedProcess:
    """The module's **only** subprocess call site."""
    alembic_bin = os.path.join(os.path.dirname(sys.executable), "alembic")
    env = {
        **os.environ,
        "POSTGRES_URL": TEST_POSTGRES_URL,
        "SECRET_KEY": "test-migration-secret",
    }
    return subprocess.run(
        [alembic_bin, *args],
        cwd=_BACKEND_DIR,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )


@pytest.fixture(scope="module")
def migrated_pg_engine():
    """Reset the target database and run the migration to head."""
    engine = create_engine(TEST_POSTGRES_URL)
    try:
        with engine.begin() as conn:
            conn.execute(text("DROP SCHEMA public CASCADE"))
            conn.execute(text("CREATE SCHEMA public"))
    except Exception as exc:  # pragma: no cover - environment-dependent  # noqa: BLE001  # any failure to reach TEST_POSTGRES_URL means skip, whatever its type
        pytest.skip(f"Could not reach TEST_POSTGRES_URL ({exc})")

    _run_alembic("upgrade", "head")

    yield engine
    engine.dispose()


def _reset_to(engine, target: str) -> None:
    """Hard-reset ``public`` and re-run the migration up to ``target``."""
    engine.dispose()  # drop pooled connections before the DDL
    with engine.begin() as conn:
        conn.execute(text("DROP SCHEMA public CASCADE"))
        conn.execute(text("CREATE SCHEMA public"))
    _run_alembic("upgrade", target)


@pytest.fixture
def isolated_pg_engine(migrated_pg_engine):
    """A database at ``head`` containing nothing but what the migration seeds.

    Resets on setup *and* on teardown, so a case using it neither inherits
    another case's committed rows nor leaks its own — in either direction,
    and regardless of execution order.
    """
    _reset_to(migrated_pg_engine, "head")
    yield migrated_pg_engine
    _reset_to(migrated_pg_engine, "head")


# ---------------------------------------------------------------------------
# The tenant partition, restated against the live schema.
# ---------------------------------------------------------------------------

# The directly-scoped tables: each carries its own NOT NULL `tenant_id`. This
# tuple is an **exact-set** assertion against the live schema at head
# (`test_inherited_tables_have_no_tenant_id` asserts
# `scoped == set(TENANT_SCOPED_TABLES) | {"user_tenant_link",
# "tenant_invitation"}`), so it has to
# grow with the schema. A new directly-scoped table registers here and thereby
# also opts into `test_every_scoped_table_has_not_null_tenant_id`.
TENANT_SCOPED_TABLES = (
    "task",
    "category",
    "role",
    "lot",
    "resident",
    "visitor",
    "visitor_authorization",
    "access_log",
    "announcement",
    "document_folder",
    "association_document",
    "occurrence",
    "package",
    "reservable_space",
    "space_reservation",
    "construction_project",
    "purchase_request",
    "asset",
    "inventory_movement",
    "access_device",
    "finance_category",
    "budget_line",
    "financial_transaction",
    "assembly",
    "vote",
    "feedback",
    "media_asset",
    "tenant_subscription",
    "infraction_rule",
    "infraction",
    "infraction_cycle_close",
    "infraction_settings",
)

# The tables that inherit their tenant through a NOT NULL parent FK and must
# therefore *not* carry a tenant_id. Asserting the absence is what stops a
# later drive-by from denormalising `ballot`.
TENANT_INHERITED_TABLES = (
    "taskcomment",
    "taskhistory",
    "task_visible_to_link",
    "user_role_link",
    "user_lot_link",
    "announcement_media",
    "announcement_comment",
    "announcement_read_receipt",
    "occurrence_timeline",
    "document_download_log",
    "project_milestone",
    "project_update",
    "purchase_quote",
    "purchase_quote_decision",
    "vote_option",
    "ballot",
    "ballot_rejection",
    "lot_voter_eligibility",
    "facial_template",
    "facial_access_event",
    "subscription_change",
    "infraction_policy_step",
    "infraction_stage",
    "infraction_contestation",
)


def _revision_modules() -> list[pathlib.Path]:
    """Every ``.py`` under ``versions/`` that is not the package marker."""
    return sorted(p for p in _VERSIONS_DIR.glob("*.py") if p.name != "__init__.py")


def _module_constant(path: pathlib.Path, name: str):
    """Read a module-level literal by ``ast``, without importing the module.

    Importing ``backend/alembic/versions/`` would shadow the real
    third-party ``alembic`` library (see `_run_alembic`).
    """
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    for node in tree.body:
        targets = (
            [node.target]
            if isinstance(node, ast.AnnAssign)
            else getattr(node, "targets", [])
        )
        for target in targets:
            if isinstance(target, ast.Name) and target.id == name:
                return ast.literal_eval(node.value)
    raise AssertionError(f"{name} not found in {path}")


def _live_tables(engine) -> set[str]:
    with engine.connect() as conn:
        return set(
            conn.execute(
                text(
                    "SELECT table_name FROM information_schema.tables "
                    "WHERE table_schema = 'public' AND table_type = 'BASE TABLE'"
                )
            )
            .scalars()
            .all()
        )


def _live_columns(engine) -> dict[str, dict[str, bool]]:
    """``{table: {column: is_nullable}}`` for the whole ``public`` schema."""
    with engine.connect() as conn:
        rows = conn.execute(
            text(
                "SELECT table_name, column_name, is_nullable "
                "FROM information_schema.columns WHERE table_schema = 'public'"
            )
        ).all()
    live: dict[str, dict[str, bool]] = {}
    for row in rows:
        live.setdefault(row.table_name, {})[row.column_name] = row.is_nullable == "YES"
    return live


# ---------------------------------------------------------------------------
# 1-2. The history is a single root revision that replays both ways.
# ---------------------------------------------------------------------------


def test_versions_holds_exactly_the_expected_revision_modules():
    """The directory is the history: no stray, no leftover, no duplicate."""
    modules = _revision_modules()

    assert [p.name for p in modules] == [f"{slug}.py" for slug in EXPECTED_HISTORY]


def test_the_history_is_a_line_from_one_root_within_the_version_num_limit():
    """One root, each later revision pointing at its predecessor, every slug
    short enough for `alembic_version.version_num`."""
    previous = None
    for expected_slug in EXPECTED_HISTORY:
        module = _VERSIONS_DIR / f"{expected_slug}.py"
        revision = _module_constant(module, "revision")

        assert revision == expected_slug
        assert len(revision) <= _REVISION_LENGTH_LIMIT
        assert _module_constant(module, "down_revision") == previous
        previous = revision

    assert previous == HEAD_REVISION


def test_no_revision_imports_anything_from_app():
    """APRAS-66 D-E, widened by APRAS-71 to **every** revision in the history.

    A live `from app.core.slug import slugify` would silently rewrite history
    the day a later task changes `slugify`, and importing under `alembic/`
    also shadows the third-party library. `0001` sets the precedent by
    re-declaring `DEFAULT_TENANT_ID` and `LEGACY_ROLE_NAMES` as literals and
    `0002` by carrying a frozen copy of the slug derivation. The claim is
    asserted by `ast` rather than by grep so an
    `importlib.import_module("app...")` could not sneak past it either.

    The loop replaces the single-module check: a revision that is no longer
    the head is no less frozen, and the case count is unchanged by it.
    """
    offenders = {}
    for slug in EXPECTED_HISTORY:
        module = _VERSIONS_DIR / f"{slug}.py"
        tree = ast.parse(module.read_text(encoding="utf-8"), filename=str(module))

        imported = set()
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                imported.update(alias.name for alias in node.names)
            elif isinstance(node, ast.ImportFrom):
                imported.add(node.module or "")
            elif isinstance(node, ast.Call):
                function = node.func
                name = getattr(function, "attr", getattr(function, "id", ""))
                if name in {"import_module", "__import__"}:
                    imported.update(
                        arg.value for arg in node.args if isinstance(arg, ast.Constant)
                    )

        bad = {name for name in imported if name == "app" or name.startswith("app.")}
        if bad:
            offenders[slug] = sorted(bad)

    assert not offenders, f"revisions importing application code: {offenders}"


def test_upgrade_downgrade_base_and_upgrade_again_all_succeed(migrated_pg_engine):
    """`downgrade base` empties the schema, and the migration replays.

    A migration that can only run once on a fresh database hides its own
    breakage until the day someone rolls back.
    """
    _reset_to(migrated_pg_engine, "head")
    assert _live_tables(migrated_pg_engine) - {"alembic_version"}

    _run_alembic("downgrade", "base")
    assert _live_tables(migrated_pg_engine) <= {"alembic_version"}

    _run_alembic("upgrade", "head")
    assert _live_tables(migrated_pg_engine) - {"alembic_version"}
    with migrated_pg_engine.connect() as conn:
        assert (
            conn.execute(text("SELECT version_num FROM alembic_version")).scalar_one()
            == HEAD_REVISION
        )


# ---------------------------------------------------------------------------
# 3-6. The schema at head is exactly what the models describe.
# ---------------------------------------------------------------------------


def test_live_table_set_equals_the_model_metadata(isolated_pg_engine):
    """Nothing missing, and nothing left over.

    `f5_backfill_journal` -- which had no model and existed only so the
    retired `0033` could roll itself back -- is caught by the "left over"
    half.
    """
    live = _live_tables(isolated_pg_engine) - {"alembic_version"}

    assert live == set(SQLModel.metadata.tables)


def test_every_column_name_and_nullability_matches_the_model(isolated_pg_engine):
    """The migration and `SQLModel.metadata` agree, column for column.

    The one check that catches the whole class of "the migration drifted from
    the models": the rest of the suite builds its schema with `create_all()`
    on SQLite, so a column the migration spells differently or leaves
    nullable would never be exercised by anything else.
    """
    live = _live_columns(isolated_pg_engine)

    for name, table in SQLModel.metadata.tables.items():
        expected = {column.name: bool(column.nullable) for column in table.columns}
        assert live[name] == expected, name


def test_the_dropped_and_the_absorbed_columns(isolated_pg_engine):
    """`role.landing_path` is gone (APRAS-57) and `0037`'s two columns stayed.

    `f5_backfill_journal` is asserted here too: it is the table whose absence
    a reader of this module will look for by name.
    """
    live = _live_columns(isolated_pg_engine)

    assert "landing_path" not in live["role"]
    assert "f5_backfill_journal" not in live
    assert live["tenant"]["logo_url"] is True
    assert live["construction_project"]["planned_progress_json"] is True


def test_no_userrole_type_and_no_user_role_column(isolated_pg_engine):
    """A Python enum deletion is not proof the Postgres type left (APRAS-27).

    SQLite would store the column as a `VARCHAR` and report nothing either
    way, which is why this case is Postgres-only.
    """
    with isolated_pg_engine.connect() as conn:
        assert conn.execute(text("SELECT to_regtype('userrole')")).scalar() is None
        labels = (
            conn.execute(
                text(
                    "SELECT enumlabel FROM pg_enum e "
                    "JOIN pg_type t ON e.enumtypid = t.oid "
                    "WHERE t.typname = 'userrole'"
                )
            )
            .scalars()
            .all()
        )
    assert labels == []
    assert "role" not in _live_columns(isolated_pg_engine)["user"]


# ---------------------------------------------------------------------------
# 7-8. The seed: one tenant, six roles, no permission.
# ---------------------------------------------------------------------------


def test_tenant_table_has_exactly_one_default_row(isolated_pg_engine):
    """The migration seeds exactly one tenant, whose id is the well-known
    default -- never a generated one, since the model default and every scoped
    column's server_default name it without a lookup. Reading the accented
    name back intact is also this module's UTF-8 check."""
    with isolated_pg_engine.connect() as conn:
        rows = conn.execute(text("SELECT id, name, is_active FROM tenant")).all()

    assert len(rows) == 1
    assert rows[0].id == DEFAULT_TENANT_ID
    assert rows[0].name == "Condomínio Padrão"
    assert rows[0].is_active is True


def test_the_default_tenants_slug_is_the_backfilled_condominio_padrao(
    isolated_pg_engine,
):
    """APRAS-66 ER-4, and the pin on `0002`'s frozen copy of the derivation.

    `Condomínio Padrão` folds to `condominio-padrao`: reading it back is both
    the backfill's assertion and a second UTF-8 check, since a cluster that
    lost the accent would produce `condomnio-padro`.
    """
    with isolated_pg_engine.connect() as conn:
        slug = conn.execute(
            text("SELECT slug FROM tenant WHERE id = :id"), {"id": DEFAULT_TENANT_ID}
        ).scalar_one()

    assert slug == "condominio-padrao"


def test_the_slug_column_is_not_null_and_uniquely_indexed(isolated_pg_engine):
    """The index is the real arbiter of a collision, so it is asserted here
    rather than inferred from the service that computes candidates."""
    with isolated_pg_engine.connect() as conn:
        nullable = conn.execute(
            text(
                "SELECT is_nullable FROM information_schema.columns "
                "WHERE table_schema = 'public' AND table_name = 'tenant' "
                "AND column_name = 'slug'"
            )
        ).scalar_one()
        definitions = (
            conn.execute(
                text(
                    "SELECT pg_get_indexdef(i.oid) FROM pg_index x "
                    "JOIN pg_class i ON i.oid = x.indexrelid "
                    "JOIN pg_class t ON t.oid = x.indrelid "
                    "JOIN pg_namespace n ON n.oid = t.relnamespace "
                    "WHERE n.nspname = 'public' AND t.relname = 'tenant' "
                    "AND x.indisunique"
                )
            )
            .scalars()
            .all()
        )

    assert nullable == "NO"
    assert any("(slug)" in definition for definition in definitions)

    with (
        pytest.raises(Exception, match=r"duplicate key|unique constraint"),
        isolated_pg_engine.begin() as conn,
    ):
        conn.execute(
            text(
                "INSERT INTO tenant (id, name, slug, is_active, created_at, "
                "updated_at) VALUES (:id, 'Outro', 'condominio-padrao', true, "
                "now(), now())"
            ),
            {"id": uuid.uuid4()},
        )


def test_rows_created_before_the_upgrade_are_backfilled_within_the_rule(
    migrated_pg_engine,
):
    """ER-4: a pre-existing two-character name yields `condominio`-something.

    The row is inserted while the database sits at `0001` -- before the
    column exists -- which is the only way to exercise the backfill rather
    than the model's construction-time fallback. A name of `AB` derives two
    characters, under the 3-64 floor, so it must come back as the
    `condominio` base plus whatever suffix the walk frees, never as `ab`.
    """
    _reset_to(migrated_pg_engine, ROOT_REVISION)

    short_id, punctuation_id = uuid.uuid4(), uuid.uuid4()
    with migrated_pg_engine.begin() as conn:
        for row_id, name in ((short_id, "AB"), (punctuation_id, "!!!")):
            conn.execute(
                text(
                    "INSERT INTO tenant (id, name, is_active, created_at, "
                    "updated_at) VALUES (:id, :name, true, now(), now())"
                ),
                {"id": row_id, "name": name},
            )

    _run_alembic("upgrade", "head")

    with migrated_pg_engine.connect() as conn:
        slugs = dict(conn.execute(text("SELECT id, slug FROM tenant")).all())

    assert slugs[DEFAULT_TENANT_ID] == "condominio-padrao"
    backfilled = {slugs[short_id], slugs[punctuation_id]}
    assert backfilled == {"condominio", "condominio-2"}
    assert len(set(slugs.values())) == len(slugs)
    low, high = _SLUG_BOUNDS
    for slug in slugs.values():
        assert _SLUG_RULE.fullmatch(slug), slug
        assert low <= len(slug) <= high, slug

    _reset_to(migrated_pg_engine, "head")


def test_the_default_tenant_owns_the_six_legacy_roles_with_no_permission(
    isolated_pg_engine,
):
    """Exactly `LEGACY_ROLE_NAMES`, unsuffixed, each granting nothing.

    No migration and no script ever seeds a permission (`app/seed.py`,
    `ensure_legacy_roles`): the pre-F5 bundle backfill the retired `0033`
    carried was a one-off rescue of a live database, not part of a fresh
    install.
    """
    with isolated_pg_engine.connect() as conn:
        rows = conn.execute(text("SELECT name, tenant_id, permissions FROM role")).all()

    assert {row.name for row in rows} == set(LEGACY_ROLE_NAMES)
    assert len(rows) == len(LEGACY_ROLE_NAMES)
    for row in rows:
        assert "(papel)" not in row.name
        assert row.tenant_id == DEFAULT_TENANT_ID
        assert row.permissions == []


# ---------------------------------------------------------------------------
# 9-10. The tenant partition and the uniques that make it usable.
# ---------------------------------------------------------------------------


def test_the_migrations_scoped_table_literal_matches_the_registry():
    """The literal two other modules read by `ast` is the runtime registry.

    `tests/test_tenant_models.py` and `tests/test_tenant_context.py` parse
    `_TENANT_SCOPED_TABLES` out of the migration; this is the case that keeps
    what they parse honest.
    """
    literal = set(
        _module_constant(_VERSIONS_DIR / f"{ROOT_REVISION}.py", "_TENANT_SCOPED_TABLES")
    )

    assert literal == {model.__tablename__ for model in TENANT_SCOPED_MODELS}
    assert literal == set(TENANT_SCOPED_TABLES)


def test_every_scoped_table_has_not_null_tenant_id(isolated_pg_engine):
    """Every directly-scoped table carries a NOT NULL tenant_id defaulting to
    the default tenant, with an ix_<table>_tenant_id index and a RESTRICT FK
    named fk_<table>_tenant_id."""
    with isolated_pg_engine.connect() as conn:
        columns = {
            (row.table_name, row.column_name): row
            for row in conn.execute(
                text(
                    "SELECT table_name, column_name, is_nullable, column_default "
                    "FROM information_schema.columns "
                    "WHERE table_schema = 'public' AND column_name = 'tenant_id'"
                )
            ).all()
        }
        indexes = set(
            conn.execute(
                text("SELECT indexname FROM pg_indexes WHERE schemaname = 'public'")
            )
            .scalars()
            .all()
        )
        restrict_fks = set(
            conn.execute(
                text(
                    "SELECT conname FROM pg_constraint "
                    "WHERE contype = 'f' AND confdeltype = 'r'"
                )
            )
            .scalars()
            .all()
        )

    for table in TENANT_SCOPED_TABLES:
        column = columns.get((table, "tenant_id"))
        assert column is not None, f"{table} has no tenant_id column"
        assert column.is_nullable == "NO", f"{table}.tenant_id is nullable"
        assert str(DEFAULT_TENANT_ID) in (column.column_default or ""), (
            f"{table}.tenant_id default is {column.column_default!r}"
        )
        assert f"ix_{table}_tenant_id" in indexes, f"{table} lacks its tenant index"
        assert f"fk_{table}_tenant_id" in restrict_fks, (
            f"{table}'s tenant FK is missing or is not ON DELETE RESTRICT"
        )


def test_inherited_tables_have_no_tenant_id(isolated_pg_engine):
    """The inherited tables must stay free of a denormalised tenant_id.

    The final assertion is an **exact set** over the live schema, so it is
    also the guard that catches a new directly-scoped table nobody registered
    in `TENANT_SCOPED_TABLES`.
    """
    with isolated_pg_engine.connect() as conn:
        scoped = set(
            conn.execute(
                text(
                    "SELECT table_name FROM information_schema.columns "
                    "WHERE table_schema = 'public' AND column_name = 'tenant_id'"
                )
            )
            .scalars()
            .all()
        )

    for table in TENANT_INHERITED_TABLES:
        assert table not in scoped, f"{table} was denormalised with a tenant_id"

    # `user` is a global identity; `user_tenant_link` is the membership
    # table; `tenant_invitation` (APRAS-71) is the third table whose
    # `tenant_id` names a tenant from **outside** it -- it is issued by a
    # superuser on a route with no acting tenant and consumed by an
    # anonymous caller, so the column is a reference and not a
    # request-scoping key. None of the three is in `TENANT_SCOPED_TABLES`,
    # in `TENANT_SCOPED_MODELS` or in `0001`'s `_TENANT_SCOPED_TABLES`.
    assert scoped == set(TENANT_SCOPED_TABLES) | {
        "user_tenant_link",
        "tenant_invitation",
    }


def _insert_second_tenant(conn) -> uuid.UUID:
    other = uuid.uuid4()
    # `slug` is NOT NULL and unique since `0002`, and nothing computes one for
    # a raw SQL insert, so the literal is spelled here.
    conn.execute(
        text(
            "INSERT INTO tenant (id, name, slug, is_active, created_at, "
            "updated_at) VALUES (:id, 'Condomínio Beta', 'condominio-beta', "
            "true, now(), now())"
        ),
        {"id": other},
    )
    return other


#: ``table -> (extra column names, extra values)`` for the per-tenant unique
#: cases: every NOT NULL column without a server default that a row needs
#: beyond ``id``/``tenant_id``, plus the unique key itself. The lists were
#: read off the live schema at head, not guessed: the migration is generated
#: from the models, which express their defaults Python-side, so Postgres
#: fills in nothing here.
_SCOPED_UNIQUES = (
    ("category", "name, color, is_active", "'Manutenção', '#808080', true"),
    ("role", "name, permissions", "'Síndico', '[]'"),
    (
        "lot",
        "block, lot_number, status, is_deleted, is_delinquent, created_at, updated_at",
        "'A', '101', 'VACANT', false, false, now(), now()",
    ),
    (
        "occurrence",
        (
            "protocol_number, is_anonymous, is_public, category, title, "
            "description, status, priority, created_at, updated_at"
        ),
        (
            "'2026-0001', false, true, 'NOISE', 'Barulho', 'Festa tardia', "
            "'OPEN', 'LOW', now(), now()"
        ),
    ),
    (
        "reservable_space",
        "name, requires_approval, is_active, created_at",
        "'Salão', false, true, now()",
    ),
    (
        "asset",
        (
            "asset_tag, name, category, location, condition, is_consumable, "
            "current_quantity, created_at, updated_at"
        ),
        (
            "'AT-1', 'Bomba', 'MANUTENCAO', 'Casa de máquinas', 'BOM', false, "
            "1, now(), now()"
        ),
    ),
    (
        "finance_category",
        "name, type, is_active, created_at, updated_at",
        "'Água', 'EXPENSE', true, now(), now()",
    ),
)


@pytest.mark.parametrize(("table", "columns", "values"), _SCOPED_UNIQUES)
def test_scoped_uniques_are_per_tenant(isolated_pg_engine, table, columns, values):
    """The same key in two tenants is fine; twice in one tenant is not."""
    insert = (
        f'INSERT INTO "{table}" (id, tenant_id, {columns}) '  # noqa: S608  # `table`, `columns` and `values` are module literals, never user input
        f"VALUES (:id, :tenant_id, {values})"
    )
    with isolated_pg_engine.begin() as conn:
        other_tenant = _insert_second_tenant(conn)
        conn.execute(text(insert), {"id": uuid.uuid4(), "tenant_id": DEFAULT_TENANT_ID})
        conn.execute(text(insert), {"id": uuid.uuid4(), "tenant_id": other_tenant})

    with (
        pytest.raises(Exception, match=r"duplicate key|unique constraint"),
        isolated_pg_engine.begin() as conn,
    ):
        conn.execute(text(insert), {"id": uuid.uuid4(), "tenant_id": DEFAULT_TENANT_ID})


def test_the_global_uniques_stay_global(isolated_pg_engine):
    """`user.email`, `user.cpf`, `tenant.name` and `access_device.device_key`
    are install-wide: a second tenant must not be able to reuse them."""
    with isolated_pg_engine.connect() as conn:
        rows = conn.execute(
            text(
                "SELECT t.relname AS table_name, i.relname AS index_name, "
                "  pg_get_indexdef(i.oid) AS definition "
                "FROM pg_index x "
                "JOIN pg_class i ON i.oid = x.indexrelid "
                "JOIN pg_class t ON t.oid = x.indrelid "
                "JOIN pg_namespace n ON n.oid = t.relnamespace "
                "WHERE n.nspname = 'public' AND x.indisunique"
            )
        ).all()

    unique_definitions = {
        (row.table_name, row.definition)
        for row in rows
        if "tenant_id" not in row.definition
    }

    for table, column in (
        ("user", "email"),
        ("user", "cpf"),
        ("tenant", "name"),
        ("access_device", "device_key"),
    ):
        assert any(
            name == table and f"({column})" in definition
            for name, definition in unique_definitions
        ), f"{table}.{column} is no longer globally unique"


# ---------------------------------------------------------------------------
# Money is NUMERIC, at the precision the migration declares (APRAS-64).
#
# This is the **sole** precision check in the task. It reads the schema the
# migration actually created, not the Python annotation and not
# `Table.columns[...].type`: SQLModel emits a bare `NUMERIC` with no precision
# for a *nullable* money column, so the metadata is not an oracle here. Six of
# the twelve are nullable, and nullability does not weaken the assertion --
# the check reads the database.
# ---------------------------------------------------------------------------

#: ``(table, column, precision, scale)`` for the twelve monetary columns.
#: ``fine_amount`` lives on ``infraction_stage``: :class:`Infraction` carries
#: no fine, its **append-only history** does (APRAS-44 §2 decision 5).
MONEY_COLUMNS = (
    ("budget_line", "planned_amount", 12, 2),
    ("financial_transaction", "amount", 12, 2),
    ("infraction_policy_step", "fine_fixed_amount", 12, 2),
    ("infraction_policy_step", "fine_fee_multiplier", 8, 4),
    ("infraction_stage", "fine_amount", 12, 2),
    ("infraction_settings", "condo_fee_amount", 12, 2),
    ("construction_project", "total_budget", 12, 2),
    ("construction_project", "executed_budget", 12, 2),
    ("project_update", "cost_impact", 12, 2),
    ("purchase_quote", "unit_price", 12, 2),
    ("plan", "base_price", 12, 2),
    ("asset", "acquisition_value", 12, 2),
)


def test_the_twelve_money_columns_are_numeric_at_the_declared_precision(
    migrated_pg_engine,
):
    with migrated_pg_engine.connect() as conn:
        rows = conn.execute(
            text(
                "SELECT table_name, column_name, data_type, numeric_precision, "
                "numeric_scale FROM information_schema.columns "
                "WHERE table_schema = 'public'"
            )
        ).all()
    live = {
        (row.table_name, row.column_name): (
            row.data_type,
            row.numeric_precision,
            row.numeric_scale,
        )
        for row in rows
    }

    observed = {}
    for table, column, _, _ in MONEY_COLUMNS:
        assert (table, column) in live, f"{table}.{column} is not in the schema"
        observed[(table, column)] = live[(table, column)]

    expected = {
        (table, column): ("numeric", precision, scale)
        for table, column, precision, scale in MONEY_COLUMNS
    }
    assert observed == expected


def test_a_decimal_round_trips_through_postgres_including_func_sum(
    isolated_pg_engine,
):
    """Insert, select and ``SUM`` return an equal ``Decimal``, exactly.

    ``SUM`` over ``NUMERIC`` is exact arithmetic in PostgreSQL; over
    ``double precision`` it is not. That difference is the whole point of the
    column type, so it is asserted rather than assumed.
    """
    from decimal import Decimal

    project_a = uuid.uuid4()
    project_b = uuid.uuid4()
    with isolated_pg_engine.begin() as conn:
        for project_id, budget in (
            (project_a, "1234.56"),
            (project_b, "0.07"),
        ):
            conn.execute(
                text(
                    "INSERT INTO construction_project "
                    "(id, tenant_id, title, total_budget, executed_budget, "
                    "physical_progress_pct, status, created_at, updated_at) "
                    "VALUES (:id, :tenant, :title, :budget, 0, 0, 'PLANNED', "
                    "NOW(), NOW())"
                ),
                {
                    "id": project_id,
                    "tenant": DEFAULT_TENANT_ID,
                    "title": f"Obra {project_id}",
                    "budget": Decimal(budget),
                },
            )

    with isolated_pg_engine.connect() as conn:
        one = conn.execute(
            text("SELECT total_budget FROM construction_project WHERE id = :id"),
            {"id": project_a},
        ).scalar_one()
        total = conn.execute(
            text("SELECT SUM(total_budget) FROM construction_project")
        ).scalar_one()

    assert isinstance(one, Decimal)
    assert one == Decimal("1234.56")
    assert isinstance(total, Decimal)
    assert total == Decimal("1234.63")


# ---------------------------------------------------------------------------
# The administrator invitation table (APRAS-71 D1, D12).
# ---------------------------------------------------------------------------


def test_tenant_invitation_exists_at_head_with_its_constraints(isolated_pg_engine):
    """`token_hash` uniquely indexed, `expires_at` NOT NULL, `accepted_at` NULL.

    The unique index is what makes "single use" arbitrable by the database
    rather than by the service that computes candidates, and `accepted_at`
    being nullable is what makes it the marker at all.
    """
    live = _live_columns(isolated_pg_engine)

    assert live["tenant_invitation"]["expires_at"] is False
    assert live["tenant_invitation"]["accepted_at"] is True
    assert live["tenant_invitation"]["accepted_user_id"] is True
    assert live["tenant_invitation"]["token_hash"] is False

    with isolated_pg_engine.connect() as conn:
        definitions = (
            conn.execute(
                text(
                    "SELECT pg_get_indexdef(i.oid) FROM pg_index x "
                    "JOIN pg_class i ON i.oid = x.indexrelid "
                    "JOIN pg_class t ON t.oid = x.indrelid "
                    "JOIN pg_namespace n ON n.oid = t.relnamespace "
                    "WHERE n.nspname = 'public' AND t.relname = 'tenant_invitation' "
                    "AND x.indisunique"
                )
            )
            .scalars()
            .all()
        )

    assert any("(token_hash)" in definition for definition in definitions)


def test_tenant_invitation_has_no_raw_token_column(isolated_pg_engine):
    """The mechanical guard against reintroducing raw-credential storage.

    The table stores a SHA-256 hex and nothing else: a stored raw token
    would turn any database dump into an account takeover, which is the
    whole reason `token_hash` is spelled the way it is.
    """
    columns = _live_columns(isolated_pg_engine)["tenant_invitation"]

    assert "token" not in columns
    assert "raw_token" not in columns
    assert "token_hash" in columns


def test_the_invitation_table_is_absent_after_downgrading_to_the_slug_revision(
    migrated_pg_engine,
):
    """`0003` rolls back cleanly, leaving `0002`'s schema exactly as it was.

    A real `alembic downgrade` from head, not a fresh `upgrade 0002`: the
    point is to exercise the revision's own `downgrade()`.
    """
    _reset_to(migrated_pg_engine, "head")
    assert "tenant_invitation" in _live_tables(migrated_pg_engine)

    _run_alembic("downgrade", "0002_tenant_slug")

    assert "tenant_invitation" not in _live_tables(migrated_pg_engine)
    with migrated_pg_engine.connect() as conn:
        assert (
            conn.execute(text("SELECT version_num FROM alembic_version")).scalar_one()
            == "0002_tenant_slug"
        )

    _reset_to(migrated_pg_engine, "head")

    assert "tenant_invitation" in _live_tables(migrated_pg_engine)
