"""ER-5: the infraction module is mechanically isolated from Financeiro.

Modelled on ``tests/test_purchase_isolation.py`` (APRAS-37), whose reasoning
applies verbatim: a raw substring scan would be both a false positive (the
unrelated legitimate module ``app.models.media_asset``) and a false negative
(``from app.models import FinancialTransaction`` contains no lowercase
``finance``). So the static half parses each of the four files with ``ast``
and inspects **import nodes** and **referenced names** only; a structural half
walks the seven tables' foreign keys in ``SQLModel.metadata``; and the runtime
half drives the whole flow through the API and counts rows.

The structural half used to be an ``ast`` scan of this module's own migration.
APRAS-58 collapsed the 39-revision history into one autogenerated revision
that creates *every* table in the database, so scanning it can no longer mean
"this module's schema" — ``SQLModel.metadata`` says the same thing about the
models the application actually runs on.

Applying a MULTA records a value, a date and the person it was applied
against. It creates **no** ledger row. When APRAS eventually grows per-lot
billing, a separate task connects them; the point of this module is that the
connection has to be a *decision* rather than a drift.
"""

from __future__ import annotations

import ast
import os
from typing import TYPE_CHECKING

import pytest
from sqlalchemy import func
from sqlmodel import SQLModel, select

from app.core import clock
from app.models.finance import BudgetLine, FinanceCategory, FinancialTransaction
from tests.infraction_helpers import (
    create_infraction,
    create_rule,
    headers,
    make_lot,
    make_member,
    make_resident,
)

if TYPE_CHECKING:  # pragma: no cover
    from fastapi.testclient import TestClient
    from sqlmodel import Session


_BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SCANNED = [
    "app/models/infraction.py",
    "app/schemas/infraction.py",
    "app/services/infraction_service.py",
    "app/api/v1/endpoints/infractions.py",
]

#: The module's own seven tables, whose foreign keys rule 3 walks.
OWN_TABLES = (
    "infraction",
    "infraction_rule",
    "infraction_policy_step",
    "infraction_stage",
    "infraction_contestation",
    "infraction_cycle_close",
    "infraction_settings",
)

FORBIDDEN_MODULES = {
    "app.models.finance",
    "app.schemas.finance",
    "app.services.finance_service",
    "app.api.v1.endpoints.finance",
}

FORBIDDEN_NAMES = {
    "FinanceCategory",
    "BudgetLine",
    "FinancialTransaction",
    "FinanceService",
}

AGGREGATE_PACKAGES = {"app.models", "app.schemas", "app.services"}

#: Every table the module's own tables may point at. `user`, `lot`,
#: `resident`, `occurrence` and `tenant` are the five foreign parents they
#: legitimately reference; none of them is a finance table.
ALLOWED_TABLES = {
    "infraction",
    "infraction_rule",
    "infraction_policy_step",
    "infraction_stage",
    "infraction_contestation",
    "infraction_cycle_close",
    "infraction_settings",
    "user",
    "lot",
    "resident",
    "occurrence",
    "tenant",
}

FINANCE_TABLES = {"financial_transaction", "finance_category", "budget_line"}

#: The finance module's own files. `test_no_finance_source_file_is_in_this_module`
#: asserts the scanned set is disjoint from it.
FINANCE_FILES = {
    "app/models/finance.py",
    "app/schemas/finance.py",
    "app/services/finance_service.py",
    "app/api/v1/endpoints/finance.py",
}


def _source(relative_path: str) -> str:
    with open(os.path.join(_BACKEND_DIR, relative_path), encoding="utf-8") as handle:
        return handle.read()


def _tree(relative_path: str) -> ast.Module:
    return ast.parse(_source(relative_path), filename=relative_path)


def _imported_modules(tree: ast.Module) -> set[str]:
    modules: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            modules.update(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
            modules.add(node.module)
    return modules


def _names_from_aggregate_packages(tree: ast.Module) -> set[str]:
    names: set[str] = set()
    for node in ast.walk(tree):
        if (
            isinstance(node, ast.ImportFrom)
            and node.level == 0
            and node.module in AGGREGATE_PACKAGES
        ):
            names.update(alias.name for alias in node.names)
    return names


def _referenced_names(tree: ast.Module) -> set[str]:
    """Every `Name` and attribute tail the file mentions.

    Wider than the import scan on purpose: it catches
    `app.models.finance.FinancialTransaction` written as an attribute chain,
    which no import node would show.
    """
    names: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Name):
            names.add(node.id)
        elif isinstance(node, ast.Attribute):
            names.add(node.attr)
    return names


# --------------------------------------------------------------------- #
# Rule 1 -- no forbidden module imports
# --------------------------------------------------------------------- #


@pytest.mark.parametrize("relative_path", SCANNED)
def test_no_forbidden_module_imports(relative_path: str) -> None:
    modules = _imported_modules(_tree(relative_path))
    offenders = modules & FORBIDDEN_MODULES
    assert not offenders, (
        f"{relative_path} imports forbidden module(s): {sorted(offenders)}"
    )


def test_rule_one_actually_catches_a_violation() -> None:
    """The scan is not vacuous."""
    tree = ast.parse("from app.models.finance import FinancialTransaction")
    assert _imported_modules(tree) & FORBIDDEN_MODULES == {"app.models.finance"}


# --------------------------------------------------------------------- #
# Rule 2 -- no forbidden names, by any spelling
# --------------------------------------------------------------------- #


@pytest.mark.parametrize("relative_path", SCANNED)
def test_no_forbidden_names(relative_path: str) -> None:
    tree = _tree(relative_path)
    offenders = (
        _names_from_aggregate_packages(tree) | _referenced_names(tree)
    ) & FORBIDDEN_NAMES
    assert not offenders, (
        f"{relative_path} names forbidden symbol(s): {sorted(offenders)}"
    )


def test_rule_two_actually_catches_a_violation() -> None:
    """`from app.models import BudgetLine` has no lowercase 'finance'."""
    tree = ast.parse("from app.models import BudgetLine, FinanceCategory")
    assert _names_from_aggregate_packages(tree) & FORBIDDEN_NAMES == {
        "BudgetLine",
        "FinanceCategory",
    }
    attribute = ast.parse("x = finance_module.FinancialTransaction")
    assert _referenced_names(attribute) & FORBIDDEN_NAMES == {"FinancialTransaction"}


# --------------------------------------------------------------------- #
# Rule 3 -- the module's tables point at no finance table
# --------------------------------------------------------------------- #


def test_the_seven_tables_reference_no_finance_table() -> None:
    """No FK of the seven infraction tables leaves ``ALLOWED_TABLES``.

    Read from ``SQLModel.metadata``: since APRAS-58 there is one
    autogenerated migration creating every table, so an ``ast`` scan of it
    would report the whole database and prove nothing about *this* module.
    """
    targets: set[str] = set()
    for name in OWN_TABLES:
        table = SQLModel.metadata.tables[name]
        for column in table.columns:
            targets.update(
                foreign_key.column.table.name for foreign_key in column.foreign_keys
            )

    assert targets, "The scan found no foreign key at all -- it is not doing its job."
    assert not targets & FINANCE_TABLES, (
        f"an infraction table points at a finance table: "
        f"{sorted(targets & FINANCE_TABLES)}"
    )
    assert targets <= ALLOWED_TABLES, (
        f"an infraction table points at foreign table(s): "
        f"{sorted(targets - ALLOWED_TABLES)}"
    )


def test_no_finance_source_file_is_in_this_module() -> None:
    """The four scanned paths are disjoint from the finance file set."""
    assert not set(SCANNED) & FINANCE_FILES
    for relative_path in SCANNED:
        assert os.path.isfile(os.path.join(_BACKEND_DIR, relative_path)), relative_path


# --------------------------------------------------------------------- #
# Runtime half -- the whole flow writes nothing into Financeiro
# --------------------------------------------------------------------- #


def test_the_full_flow_writes_no_finance_row(
    client: TestClient, session: Session
) -> None:
    """settings → rule → policy → infraction → advance to MULTA, and count."""
    staff = make_member(session, profile="ADMINISTRATOR", seed=1)
    lot = make_lot(session)
    resident = make_resident(session, lot, seed=10)

    def _counts() -> tuple[int, int, int]:
        return tuple(
            session.exec(select(func.count()).select_from(model)).one()
            for model in (FinancialTransaction, FinanceCategory, BudgetLine)
        )

    # Virgin world.
    assert _counts() == (0, 0, 0)
    before = _counts()

    assert (
        client.put(
            "/api/v1/infraction-settings",
            json={"condo_fee_amount": 400.0},
            headers=headers(staff),
        ).status_code
        == 200
    )
    rule_id = create_rule(
        client,
        staff,
        steps=[
            {
                "step_order": 1,
                "action": "MULTA",
                "fine_mode": "MULTIPLE",
                "fine_fee_multiplier": 2.0,
            }
        ],
    )
    infraction = create_infraction(
        client,
        staff,
        rule_id=rule_id,
        lot=lot,
        resident=resident,
        occurred_on=clock.today_utc(),
    )
    applied = client.post(
        f"/api/v1/infractions/{infraction['id']}/stages",
        json={"note": "Multa aplicada."},
        headers=headers(staff),
    )
    assert applied.status_code == 201, applied.text

    # ER-5: a MULTA records a value, a date and the person it was applied
    # against -- and nothing else anywhere.
    entry = applied.json()["timeline"][0]
    assert entry["fine_amount"] == 800.0
    assert applied.json()["responsible"]["id"] == str(resident.id)
    assert _counts() == before == (0, 0, 0)
