"""Mechanical proof that the purchase-quotation module (APRAS-37) is isolated.

The no-integration constraint from the spec is a hard requirement, not a
preference: choosing a quote must create no ``FinancialTransaction``, no
``InventoryMovement``, no ``Asset`` and no link to a ``ConstructionProject``.

This module proves it two ways:

* **Statically**, by parsing each of the four files of the module with
  ``ast.parse()`` and inspecting its import nodes. A raw substring scan is
  deliberately *not* used: it would be both a false positive (the unrelated
  legitimate module ``app.models.media_asset``) and a false negative (``from
  app.models import Asset`` contains no lowercase ``asset``).
* **Structurally**, over ``SQLModel.metadata``: every foreign key of the
  module's three tables must point inside the module (plus ``user``). This
  used to be an ``ast`` scan of the module's own migration, but APRAS-58
  collapsed the history into a single autogenerated revision that creates
  *every* table in the database — so scanning it can no longer mean "this
  module's schema". The metadata says the same thing, and says it about the
  models the application actually runs on.
* **At runtime**, by driving the whole flow through the API and asserting the
  four foreign tables stay empty.
"""

import ast
import os
import uuid

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import func
from sqlmodel import Session, SQLModel, select

from app.core.security import create_access_token
from app.models.asset import Asset, InventoryMovement
from app.models.finance import FinancialTransaction
from app.models.project import ConstructionProject
from app.models.user import User
from tests.conftest import make_user

_BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SCANNED = [
    "app/models/purchase.py",
    "app/schemas/purchase.py",
    "app/services/purchase_service.py",
    "app/api/v1/endpoints/purchases.py",
]

#: The module's own tables, whose foreign keys rule 3 checks.
OWN_TABLES = ("purchase_request", "purchase_quote", "purchase_quote_decision")

FORBIDDEN_MODULES = {
    "app.models.finance",
    "app.models.asset",
    "app.models.project",
    "app.schemas.finance",
    "app.schemas.asset",
    "app.schemas.project",
    "app.services.finance_service",
    "app.services.asset_service",
    "app.services.project_service",
    "app.api.v1.endpoints.finance",
    "app.api.v1.endpoints.assets",
    "app.api.v1.endpoints.inventory_movements",
    "app.api.v1.endpoints.projects",
}

FORBIDDEN_NAMES = {
    "FinanceCategory",
    "BudgetLine",
    "FinancialTransaction",
    "Asset",
    "InventoryMovement",
    "ConstructionProject",
    "ProjectMilestone",
    "ProjectUpdate",
    "FinanceService",
    "AssetService",
    "ProjectService",
}

AGGREGATE_PACKAGES = {"app.models", "app.schemas", "app.services"}

ALLOWED_TABLES = {
    "purchase_request",
    "purchase_quote",
    "purchase_quote_decision",
    "user",
    # The tenant FK every directly-scoped table carries (APRAS-41). It is not
    # an integration with another module: it is the partition itself.
    "tenant",
}


def _source(relative_path: str) -> str:
    with open(os.path.join(_BACKEND_DIR, relative_path), encoding="utf-8") as handle:
        return handle.read()


def _tree(relative_path: str) -> ast.Module:
    return ast.parse(_source(relative_path), filename=relative_path)


def _imported_modules(tree: ast.Module) -> set[str]:
    """Full dotted module paths imported by the file (absolute imports only)."""
    modules: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            modules.update(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
            modules.add(node.module)
    return modules


def _names_from_aggregate_packages(tree: ast.Module) -> set[str]:
    """Names imported through ``app.models`` / ``app.schemas`` / ``app.services``."""
    names: set[str] = set()
    for node in ast.walk(tree):
        if (
            isinstance(node, ast.ImportFrom)
            and node.level == 0
            and node.module in AGGREGATE_PACKAGES
        ):
            names.update(alias.name for alias in node.names)
    return names


# --------------------------------------------------------------------- #
# Rule 1 — no forbidden module imports
# --------------------------------------------------------------------- #


@pytest.mark.parametrize("relative_path", SCANNED)
def test_no_forbidden_module_imports(relative_path: str) -> None:
    modules = _imported_modules(_tree(relative_path))
    offenders = modules & FORBIDDEN_MODULES
    assert not offenders, (
        f"{relative_path} imports forbidden module(s): {sorted(offenders)}"
    )


def test_media_asset_is_not_treated_as_forbidden() -> None:
    """`app.models.media_asset` must survive the rule-1 comparison."""
    tree = ast.parse("from app.models.media_asset import MediaAsset")
    assert not _imported_modules(tree) & FORBIDDEN_MODULES


def test_rule_one_actually_catches_a_violation() -> None:
    """The scan is not vacuous: a real forbidden import must be detected."""
    tree = ast.parse("from app.models.asset import Asset")
    assert _imported_modules(tree) & FORBIDDEN_MODULES == {"app.models.asset"}


# --------------------------------------------------------------------- #
# Rule 2 — no forbidden names re-exported through the aggregate packages
# --------------------------------------------------------------------- #


@pytest.mark.parametrize("relative_path", SCANNED)
def test_no_forbidden_names_via_aggregate_packages(relative_path: str) -> None:
    names = _names_from_aggregate_packages(_tree(relative_path))
    offenders = names & FORBIDDEN_NAMES
    assert not offenders, (
        f"{relative_path} imports forbidden name(s) through an aggregate "
        f"package: {sorted(offenders)}"
    )


def test_rule_two_actually_catches_a_violation() -> None:
    """`from app.models import Asset` has no lowercase 'asset' — rule 2 sees it."""
    tree = ast.parse("from app.models import Asset, InventoryMovement")
    assert _names_from_aggregate_packages(tree) & FORBIDDEN_NAMES == {
        "Asset",
        "InventoryMovement",
    }


# --------------------------------------------------------------------- #
# Rule 3 — the module's tables reach no foreign table
# --------------------------------------------------------------------- #


def test_the_modules_tables_have_no_foreign_key_outside_the_module() -> None:
    """No FK of the three purchase tables leaves ``ALLOWED_TABLES``.

    Read from ``SQLModel.metadata`` rather than from a migration: since
    APRAS-58 there is one autogenerated revision creating every table, so an
    ``ast`` scan of it would report the whole database and prove nothing about
    *this* module.
    """
    targets: set[str] = set()
    for name in OWN_TABLES:
        table = SQLModel.metadata.tables[name]
        for column in table.columns:
            targets.update(
                foreign_key.column.table.name for foreign_key in column.foreign_keys
            )

    assert targets, "The scan found no foreign key at all — it is not doing its job."
    assert targets <= ALLOWED_TABLES, (
        f"A purchase table points at foreign table(s): "
        f"{sorted(targets - ALLOWED_TABLES)}"
    )


def test_every_scanned_file_exists() -> None:
    for relative_path in SCANNED:
        assert os.path.isfile(os.path.join(_BACKEND_DIR, relative_path)), relative_path


# --------------------------------------------------------------------- #
# Runtime half — the flow writes nothing outside its own tables
# --------------------------------------------------------------------- #


def _headers(user: User) -> dict[str, str]:
    return {"Authorization": f"Bearer {create_access_token(user.id)}"}


@pytest.fixture
def board_user(session: Session) -> User:
    user = make_user(
        session,
        id=uuid.uuid4(),
        email="board_iso@test.com",
        full_name="Board Member",
        hashed_password="hash",
        profile="DIRECTOR",
        cpf="99999999999",
    )
    session.add(user)
    session.commit()
    session.refresh(user)
    return user


def test_full_flow_writes_nothing_into_finance_inventory_assets_or_projects(
    client: TestClient, session: Session, board_user: User
) -> None:
    request_id = client.post(
        "/api/v1/purchase-requests",
        json={
            "title": "Compra de bombas",
            "description": "Duas bombas submersas",
            "general_notes": "Verba do fundo de obras (apenas anotação)",
        },
        headers=_headers(board_user),
    ).json()["id"]

    first = client.post(
        f"/api/v1/purchase-requests/{request_id}/quotes",
        json={
            "supplier_name": "Hidráulica Central",
            "items": [
                {
                    "description": "Bomba submersa",
                    "quantity": 2,
                    "unit_price": 1500.0,
                }
            ],
            "extra_fields": [{"label": "Prazo", "value": "20 dias"}],
        },
        headers=_headers(board_user),
    )
    assert first.status_code == 201
    second = client.post(
        f"/api/v1/purchase-requests/{request_id}/quotes",
        json={
            "supplier_name": "Bombas & Cia",
            "items": [
                {
                    "description": "Bomba submersa",
                    "quantity": 2,
                    "unit_price": 1200.0,
                }
            ],
        },
        headers=_headers(board_user),
    )
    assert second.status_code == 201

    decision = client.post(
        f"/api/v1/purchase-requests/{request_id}/decision",
        json={
            "quote_id": second.json()["id"],
            "justification": "Menor preço e mesmo prazo de entrega.",
        },
        headers=_headers(board_user),
    )
    assert decision.status_code == 201

    for model in (FinancialTransaction, InventoryMovement, Asset, ConstructionProject):
        count = session.exec(select(func.count()).select_from(model)).one()
        assert count == 0, f"{model.__name__} must stay empty after a purchase flow."
