"""Where uploaded and generated bytes go, and who decides (APRAS-94).

Until this module became configuration-driven, every write went to local disk
through a provider five services instantiated themselves. On Vercel the
function's filesystem is read-only outside ``/tmp``, so the ``mkdir`` in
:meth:`LocalStorageProvider.save_file` raised ``OSError`` and the exception
escaped the route -- and Starlette mounts ``ServerErrorMiddleware`` *outside*
``CORSMiddleware``, so the answer was a bodiless 500 with no
``access-control-allow-origin``, which every browser reports as a CORS error.
Uploading a condominium logo in production failed for that reason, and so did
the obras report and the assembly minutes.

Two rules follow, and the module is arranged around them:

1. :func:`upload_storage_provider` and :func:`generated_storage_provider` are
   the **only** places a provider is built. With ``BLOB_READ_WRITE_TOKEN`` set
   they hand back a Vercel Blob provider for their own namespace; without it
   they hand back exactly the ``LocalStorageProvider`` -- same ``base_dir``,
   same ``url_prefix`` -- every caller used before, so local development and
   the test suite are unchanged.
2. **No storage failure escapes unhandled.** Every one of them, on every
   provider, becomes :class:`~app.core.exceptions.StorageUnavailableError`
   (503) or, for a content type that may not be stored at all,
   :class:`~app.core.exceptions.UnsupportedStorageContentTypeError` (422).
   ``delete_file`` keeps a best-effort contract on every provider: it returns
   ``bool`` and never raises, so a failed cleanup cannot fail a request.
"""

import abc
import os
import uuid
from pathlib import Path
from urllib.parse import urlencode, urlparse
from uuid import UUID

import httpx

from app.core import clock
from app.core.config import settings
from app.core.exceptions import (
    StorageUnavailableError,
    UnsupportedStorageContentTypeError,
)
from app.core.uploads import canonical_content_type, canonical_extension
from app.models.enums import StorageProvider


class BaseStorageProvider(abc.ABC):
    """Abstract interface for media asset storage providers."""

    #: Which backend actually holds the bytes. ``media_assets.storage_provider``
    #: records this rather than a hard-coded ``LOCAL_DISK``. The default is the
    #: disk because every in-tree test double inherits it and writes nowhere
    #: else; a provider that stores elsewhere overrides it.
    provider_kind: StorageProvider = StorageProvider.LOCAL_DISK

    @abc.abstractmethod
    def save_file(
        self,
        file_bytes: bytes,
        filename: str,
        content_type: str,
        *,
        tenant_id: UUID | None = None,
    ) -> tuple[str, str]:
        """
        Save file bytes to storage backend.

        ``tenant_id`` is the acting tenant, for namespacing an object path. It
        is an argument and not ambient state because the acting tenant is a
        session-level fact with no ``ContextVar`` to read it from, and it is
        **not** a security boundary: a provider is free to ignore it, as the
        local one does.

        Returns:
            Tuple[str, str]: (internal_file_path, public_or_relative_url)
        """

    @abc.abstractmethod
    def delete_file(self, file_path: str) -> bool:
        """
        Delete a stored file by its internal file path.

        Returns:
            bool: True if deleted successfully or missing, False otherwise.
        """

    def resolve_stored_path(self, url: str | None) -> str | None:
        """What this provider would delete to remove ``url``, or ``None``.

        The replacement for the ``/static/uploads/`` prefix check
        ``tenant_service`` and ``purchase_service`` each carried: that
        predicate silently skipped every Blob URL, orphaning the object it
        should have removed. ``None`` keeps APRAS-61's rule intact -- a URL
        this provider did not mint is somebody else's file and is left alone.

        The default is ``None``: a provider that cannot map a URL back to
        something it owns, which includes every stub and every test double,
        owns nothing.
        """
        del url
        return None

    def resolve_own_url(self, url: str | None) -> Path | None:
        """The path under this provider's **own** root that ``url`` names.

        The read-side companion of :meth:`resolve_stored_path`, and the one
        place the "``/static/uploads/`` maps back to ``base_dir``" rule is
        stated. ``None`` means *this provider does not own that value*, which
        includes every stub, every test double and every remote store.
        """
        del url
        return None

    def read_file(self, url: str | None) -> bytes | None:
        """The bytes behind one of this provider's **own** URLs, or ``None``.

        A **concrete** default, deliberately: "this backend cannot read its own
        objects back". The three unimplemented provider stubs therefore stay
        untouched and no unimplemented-method exception can reach a client --
        the property ``tests/test_storage_blob.py`` holds by text scan over this
        module. Vercel Blob inherits the default too, so a Blob-stored logo
        takes APRAS-92 §B's rung 2 (a linked ``<img src>``) until **APRAS-96**
        gives that provider a real ``read_file``.

        Never a network call on any provider that implements it against a
        remote store without saying so: the one caller
        (``TenantService.logo_data_uri``) runs inside an unauthenticated,
        uncached render.
        """
        del url
        return None


#: Where user-supplied uploads live, and the prefix the mount serving them
#: answers on. That mount forces a download for anything outside
#: ``INLINE_SAFE_EXTENSIONS``.
DEFAULT_UPLOAD_BASE_DIR = "static/uploads"
DEFAULT_UPLOAD_URL_PREFIX = "/static/uploads"

#: Where output **this application renders itself** lives, and its prefix. The
#: mount serving it renders inline, which is only safe because nothing a client
#: supplies is ever written here -- see :func:`generated_storage_provider`.
GENERATED_BASE_DIR = "static/generated"
GENERATED_URL_PREFIX = "/static/generated"

#: The first segment of a Blob object's pathname, one per tree. The same split
#: the two static mounts express, carried onto a store that has no mounts.
UPLOAD_NAMESPACE = "uploads"
GENERATED_NAMESPACE = "generated"

#: The pathname segment standing in for an acting tenant when a write happens
#: outside any tenant scope.
SHARED_NAMESPACE_SEGMENT = "shared"


class LocalStorageProvider(BaseStorageProvider):
    """Local disk storage provider saving to {base_dir}/{year}/{month}/."""

    provider_kind = StorageProvider.LOCAL_DISK

    def __init__(
        self,
        base_dir: str | Path = DEFAULT_UPLOAD_BASE_DIR,
        url_prefix: str = DEFAULT_UPLOAD_URL_PREFIX,
    ) -> None:
        """``url_prefix`` is paired with ``base_dir``: it is what the mount
        serving that directory answers on, and both default to the upload
        tree so every existing caller mints exactly the URL it minted before.
        """
        self.base_dir = Path(base_dir)
        self.url_prefix = url_prefix.rstrip("/")

    def save_file(
        self,
        file_bytes: bytes,
        filename: str,
        content_type: str,
        *,
        tenant_id: UUID | None = None,
    ) -> tuple[str, str]:
        """Write the bytes under a UUID name whose suffix comes from the type.

        ``filename`` is **display metadata and nothing else**: it does not
        reach the disk. The suffix is derived from the already-validated
        ``content_type`` instead, because the static mount guesses what it
        serves from the extension and the client must not get to choose it
        (APRAS-65). An unmapped type yields an inert ``.bin``.

        ``tenant_id`` is ignored: this tree's layout is ``{year}/{month}``, and
        namespacing by tenant is a property of the Blob pathname alone. Both
        unused arguments are dropped with ``del`` rather than two ``noqa``
        directives, whose count ``tests/test_lint_hygiene.py`` caps.
        """
        del filename, tenant_id

        now = clock.db_now()
        year_month_subfolder = f"{now.year}/{now.month:02d}"
        target_dir = self.base_dir / year_month_subfolder
        try:
            target_dir.mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            # The belt to the braces (APRAS-94 §6): with no Blob token
            # configured, a serverless deploy lands here, and it must answer
            # with a diagnosable body instead of crashing the route.
            raise StorageUnavailableError(
                "o sistema de arquivos é somente leitura (read-only file "
                "system) e nenhum armazenamento remoto está configurado; "
                "defina BLOB_READ_WRITE_TOKEN"
            ) from exc

        unique_name = f"{uuid.uuid4()}{canonical_extension(content_type)}"
        relative_path = os.path.join(year_month_subfolder, unique_name)
        full_path = target_dir / unique_name

        try:
            with open(full_path, "wb") as f:
                f.write(file_bytes)
        except OSError as exc:
            raise StorageUnavailableError(
                f"falha ao gravar em disco: {exc.strerror or exc}"
            ) from exc

        url = f"{self.url_prefix}/{relative_path}"
        return str(full_path), url

    def delete_file(self, file_path: str) -> bool:
        try:
            path = Path(file_path)
            if path.exists():
                path.unlink()
            return True
        except Exception:  # noqa: BLE001  # best-effort side effect; a failure here must not fail the request
            return False

    def resolve_stored_path(self, url: str | None) -> str | None:
        """Map one of **this instance's own** URLs back to a path on disk.

        Keyed off ``self.url_prefix`` and never off a module-level
        ``/static/uploads`` literal, so the ``static/generated`` instance
        resolves its own values too. The path is built relative to
        ``base_dir`` rather than by stripping the leading slash: identical for
        the production provider and honest for any other one.
        """
        prefix = f"{self.url_prefix}/"
        if url is None or not url.startswith(prefix):
            return None
        return str(self.base_dir / url[len(prefix) :])

    def resolve_own_url(self, url: str | None) -> Path | None:
        """:meth:`resolve_stored_path`, plus a containment check (APRAS-92 §B).

        The prefix rule is not restated: it is asked of
        :meth:`resolve_stored_path`, so "what this provider owns" has one
        definition for reads and for deletes alike.

        What is added is the check the delete path never had. A stored
        ``logo_url`` is **data**, and a read primitive invoked from a public,
        unauthenticated route must not depend on who wrote it: the joined path
        is resolved and refused unless it is still inside ``base_dir``, so
        ``/static/uploads/../../../etc/passwd`` maps to nothing. Not reachable
        today -- the only writer is the validated upload path -- which is
        exactly why it is cheap defence in depth rather than a fix.
        """
        stored = self.resolve_stored_path(url)
        if stored is None:
            return None
        root = self.base_dir.resolve()
        candidate = Path(stored).resolve()
        if not candidate.is_relative_to(root):
            return None
        return candidate

    def read_file(self, url: str | None) -> bytes | None:
        """The bytes of one of this provider's own files, or ``None``.

        ``None`` for a value this provider does not own, for one that escapes
        its root, and for a file that is missing or unreadable: a caller
        embedding a logo degrades, it does not fail.
        """
        path = self.resolve_own_url(url)
        if path is None:
            return None
        try:
            return path.read_bytes()
        except OSError:
            return None


#: Vercel's Blob REST API, as read out of ``@vercel/blob`` 2.6.1's own compiled
#: client in ``repertoire_hero/node_modules/@vercel/blob/dist`` (``getApiUrl``,
#: ``requestApi``, ``createPutHeaders``, ``del``) rather than out of prose
#: documentation. There is no published REST reference, so the version is
#: pinned and named: **a 4xx naming the API version is the signal to bump this
#: constant**, and the mapped error carries the API's own code and message so
#: that signal is observable in production rather than guessed at.
BLOB_API_BASE_URL = "https://vercel.com/api/blob"
BLOB_API_VERSION = "12"

#: The host every public Blob object is served from. Used to decide whether a
#: stored value is one of ours (:meth:`BaseStorageProvider.resolve_stored_path`).
BLOB_HOST_SUFFIX = ".blob.vercel-storage.com"

#: Where the store id sits in a ``vercel_blob_rw_<storeId>_<random>`` token,
#: reading it exactly as the SDK's ``parseStoreIdFromReadWriteToken`` does.
BLOB_TOKEN_STORE_ID_FIELD = 3

#: Explicitly bounded on every phase: an unbounded default read timeout would
#: hold a serverless invocation (and, locally, the event loop) for as long as
#: the API takes to answer.
BLOB_TIMEOUT = httpx.Timeout(connect=5.0, read=30.0, write=30.0, pool=5.0)


class VercelBlobStorageProvider(BaseStorageProvider):
    """Vercel Blob storage over its REST API, with no new dependency.

    ``httpx`` is already a dependency and the REST contract suffices, so the
    ``@vercel/blob`` SDK (a Node package) is not needed. The client is the
    **synchronous** one: every ``save_file`` caller is a synchronous service
    function, and a function running on the event loop thread cannot await an
    offload. That blocks the loop for the duration of an upload -- accepted
    deliberately (APRAS-94, "The blocking call"): these routes already run
    synchronous SQLAlchemy work inline, a Vercel invocation serves one request,
    and the timeout above bounds the worst case. The cheap upgrade, if local
    latency ever matters, is ``run_in_threadpool`` at the *route* boundary,
    which needs no change here.
    """

    provider_kind = StorageProvider.VERCEL_BLOB

    def __init__(
        self,
        *,
        namespace: str,
        token: str | None,
        allow_html: bool = False,
    ) -> None:
        """``allow_html`` is the two static mounts' split, carried onto Blob.

        Only the instance :func:`generated_storage_provider` returns accepts
        ``text/html``, because only server-rendered output is written there.
        The instance :func:`upload_storage_provider` returns refuses it, which
        is what the uploads mount's forced download does today.
        """
        self.namespace = namespace
        self.token = token
        self.allow_html = allow_html

    # -- the contract ------------------------------------------------------

    def save_file(
        self,
        file_bytes: bytes,
        filename: str,
        content_type: str,
        *,
        tenant_id: UUID | None = None,
    ) -> tuple[str, str]:
        """``PUT`` the bytes under a freshly minted UUID pathname.

        ``filename`` is unused for exactly the reason it is unused on disk: it
        is display metadata, and the stored suffix comes from the validated
        ``content_type`` (APRAS-65). Dropped with ``del`` rather than a
        ``noqa``, whose count ``tests/test_lint_hygiene.py`` caps.

        Both return values are the blob URL: callers that persisted
        ``file_path`` (finance, announcements, media) delete through the same
        value as callers that persisted the URL.
        """
        del filename

        stored_type = self._assert_storable(content_type)
        store_id = self._store_id()
        pathname = self._pathname(stored_type, tenant_id)

        response = self._request(
            "PUT",
            f"{BLOB_API_BASE_URL}/?{urlencode({'pathname': pathname})}",
            headers={
                **self._auth_headers(store_id),
                "x-vercel-blob-access": "public",
                "x-content-type": stored_type,
                # The object name is already a UUID, so there is nothing to
                # disambiguate. `x-allow-overwrite` is deliberately **not**
                # sent: an overwrite cannot legitimately occur, so a collision
                # must stay an error rather than silently replace an object.
                "x-add-random-suffix": "0",
            },
            content=file_bytes,
        )
        if not response.is_success:
            raise StorageUnavailableError(self._describe(response))

        url = self._url_of(response)
        return url, url

    def delete_file(self, file_path: str) -> bool:
        """Best-effort removal. Never raises, and never guesses.

        A value :meth:`resolve_stored_path` rejects -- a filesystem path
        written before the token was configured, an externally hosted URL --
        makes **no HTTP call at all**: it is not this store's object, so
        POSTing it to the delete endpoint could only ever be noise.
        """
        if self.resolve_stored_path(file_path) is None:
            return False
        try:
            response = self._request(
                "POST",
                f"{BLOB_API_BASE_URL}/delete",
                headers={
                    **self._auth_headers(self._store_id()),
                    "content-type": "application/json",
                },
                json={"urls": [file_path]},
            )
        except StorageUnavailableError:
            return False
        return response.is_success

    def resolve_stored_path(self, url: str | None) -> str | None:
        """The URL itself when it is a Blob object's, else ``None``."""
        if not url:
            return None
        host = urlparse(url).hostname or ""
        return url if host.endswith(BLOB_HOST_SUFFIX) else None

    # -- the request -------------------------------------------------------

    def _store_id(self) -> str:
        """The fourth ``_``-separated field of the read-write token.

        Exactly what the SDK's ``parseStoreIdFromReadWriteToken`` reads out of
        ``vercel_blob_rw_<storeId>_<random>``. A token that does not yield one
        is a configuration fault, diagnosed at the point of use and named so an
        operator knows which variable to fix.
        """
        token = self.token or ""
        # A header value httpx cannot encode raises `UnicodeEncodeError` from
        # deep inside the transport -- outside the `httpx.HTTPError` family
        # `_request` maps, so it would escape unhandled and reproduce the very
        # bodiless, CORS-header-less 500 this provider exists to remove. A
        # pasted smart quote in the Vercel dashboard is enough. Refuse here,
        # where the fault is named, rather than at the socket.
        if not token.isascii():
            raise StorageUnavailableError(
                "BLOB_READ_WRITE_TOKEN contém caracteres não-ASCII; "
                "reconfigure a variável de ambiente BLOB_READ_WRITE_TOKEN "
                "copiando o valor exato do painel do Vercel Blob"
            )
        fields = token.split("_")
        store_id = (
            fields[BLOB_TOKEN_STORE_ID_FIELD]
            if len(fields) > BLOB_TOKEN_STORE_ID_FIELD
            else ""
        )
        if not store_id:
            raise StorageUnavailableError(
                "BLOB_READ_WRITE_TOKEN ausente ou malformado; configure a "
                "variável de ambiente BLOB_READ_WRITE_TOKEN do Vercel Blob"
            )
        return store_id

    def _auth_headers(self, store_id: str) -> dict[str, str]:
        return {
            "authorization": f"Bearer {self.token}",
            "x-api-version": BLOB_API_VERSION,
            "x-vercel-blob-store-id": store_id,
        }

    def _assert_storable(self, content_type: str) -> str:
        """The canonical type to store as, or a 422.

        A Blob object is served by Vercel's CDN and never passes through
        ``HardenedStaticFiles``, so the mount's forced download for unsafe
        extensions is unavailable. What replaces it is refusing anything
        ``app.core.uploads`` does not name, plus ``text/html`` outside the
        generated namespace. Stricter than the disk's inert ``.bin``, and
        unreachable from any endpoint: every service allowlist is a subset of
        ``CONTENT_TYPE_EXTENSIONS`` (``tests/test_upload_filename_safety.py``).
        """
        stored_type = canonical_content_type(content_type)
        if stored_type is None or (stored_type == "text/html" and not self.allow_html):
            raise UnsupportedStorageContentTypeError(content_type)
        return stored_type

    def _pathname(self, stored_type: str, tenant_id: UUID | None) -> str:
        """``{namespace}/{tenant or shared}/{year}/{month}/{uuid}{ext}``.

        The tenant segment is operational -- offboarding, attribution,
        debugging -- and not a security boundary: public Blob URLs are
        unguessable either way.
        """
        now = clock.db_now()
        tenant_segment = (
            str(tenant_id) if tenant_id is not None else SHARED_NAMESPACE_SEGMENT
        )
        name = f"{uuid.uuid4()}{canonical_extension(stored_type)}"
        return f"{self.namespace}/{tenant_segment}/{now.year}/{now.month:02d}/{name}"

    def _request(self, method: str, url: str, **kwargs) -> httpx.Response:
        try:
            with httpx.Client(timeout=BLOB_TIMEOUT) as client:
                return client.request(method, url, **kwargs)
        except httpx.HTTPError as exc:
            raise StorageUnavailableError(
                f"falha de comunicação com o Vercel Blob: {exc}"
            ) from exc

    # -- the response ------------------------------------------------------

    @staticmethod
    def _payload(response: httpx.Response) -> object | None:
        """The parsed body, or ``None`` when it is not JSON.

        Nothing subscripts a ``json()`` result before it has been validated: a
        response-shape change on a 2xx would otherwise raise
        ``JSONDecodeError``/``KeyError`` out of ``save_file`` and reproduce the
        bodiless, header-less 500 this whole task exists to eliminate.
        """
        try:
            return response.json()
        except ValueError:
            return None

    @classmethod
    def _describe(cls, response: httpx.Response) -> str:
        """The status, plus the API's own ``error.code``/``error.message``.

        Carried into the raised message whenever the body supplies them, so "a
        4xx naming the API version is the signal to bump the constant" is an
        observable production signal and not a guess.
        """
        detail = ""
        payload = cls._payload(response)
        if isinstance(payload, dict):
            error = payload.get("error")
            if isinstance(error, dict):
                parts = [
                    str(error[key]) for key in ("code", "message") if error.get(key)
                ]
                detail = f" ({': '.join(parts)})" if parts else ""
        return f"o Vercel Blob respondeu {response.status_code}{detail}"

    @classmethod
    def _url_of(cls, response: httpx.Response) -> str:
        """The ``url`` of a successful response, validated before it is used."""
        payload = cls._payload(response)
        url = payload.get("url") if isinstance(payload, dict) else None
        if not isinstance(url, str) or not url:
            raise StorageUnavailableError(
                "o Vercel Blob respondeu "
                f"{response.status_code} sem uma URL utilizável; o contrato da "
                f"API (x-api-version {BLOB_API_VERSION}) pode ter mudado"
            )
        return url


def upload_storage_provider() -> BaseStorageProvider:
    """The provider every **client-supplied** upload is written through.

    One of exactly two decision points, and the reason no service names a
    provider class any more: five modules used to bind
    ``LocalStorageProvider()`` themselves, so making uploads work on a
    read-only filesystem would have meant five edits and five chances to miss
    one. With no token configured this returns byte-for-byte today's provider,
    which is what keeps local development and the whole suite unchanged.
    """
    if settings.BLOB_READ_WRITE_TOKEN:
        return VercelBlobStorageProvider(
            namespace=UPLOAD_NAMESPACE, token=settings.BLOB_READ_WRITE_TOKEN
        )
    return LocalStorageProvider(
        base_dir=DEFAULT_UPLOAD_BASE_DIR, url_prefix=DEFAULT_UPLOAD_URL_PREFIX
    )


def generated_storage_provider() -> BaseStorageProvider:
    """The provider the assembly-minutes and works-report generators use.

    Server-rendered HTML has to be served inline to be of any use, and the
    upload mount refuses to do that for a good reason. So generated output
    gets its own tree and its own mount. This factory is the **only** way any
    service reaches that tree: no call site names the directory itself, so
    "what can land next to inline-rendered HTML" stays answerable by reading
    this one function's callers -- and on Blob, where there is no mount at all,
    ``allow_html`` is what carries that same split.
    """
    if settings.BLOB_READ_WRITE_TOKEN:
        return VercelBlobStorageProvider(
            namespace=GENERATED_NAMESPACE,
            token=settings.BLOB_READ_WRITE_TOKEN,
            allow_html=True,
        )
    return LocalStorageProvider(
        base_dir=GENERATED_BASE_DIR, url_prefix=GENERATED_URL_PREFIX
    )


class _UnconfiguredStorageProvider(BaseStorageProvider):
    """A backend this deployment has no implementation for.

    The two stubs below used to raise a bare not-implemented builtin from both
    methods, which is an unhandled exception: it escapes the route, bypasses
    ``CORSMiddleware`` and produces the bodiless 500 that started this task.
    Both raise the mapped 503 instead (APRAS-94 §6) -- the best-effort
    ``delete_file`` contract belongs to the two providers that can actually
    store something, and a stub reporting a clean ``False`` would claim a
    cleanup it never attempted.
    """

    #: Named in the error, so the body says which backend is missing.
    backend_name = "desconhecido"

    def save_file(
        self,
        file_bytes: bytes,
        filename: str,
        content_type: str,
        *,
        tenant_id: UUID | None = None,
    ) -> tuple[str, str]:
        del file_bytes, filename, content_type, tenant_id
        raise self._unavailable()

    def delete_file(self, file_path: str) -> bool:
        del file_path
        raise self._unavailable()

    def _unavailable(self) -> StorageUnavailableError:
        return StorageUnavailableError(
            f"o provedor {self.backend_name} não está implementado nesta instalação"
        )


class S3StorageProvider(_UnconfiguredStorageProvider):
    """Unimplemented AWS S3 storage provider (out of scope for APRAS-94)."""

    provider_kind = StorageProvider.AWS_S3
    backend_name = "AWS S3"


class CloudinaryStorageProvider(_UnconfiguredStorageProvider):
    """Unimplemented Cloudinary storage provider (out of scope for APRAS-94)."""

    provider_kind = StorageProvider.CLOUDINARY
    backend_name = "Cloudinary"
