"""Where uploaded and generated bytes go, and who decides (APRAS-94).

Until this module became configuration-driven, every write went to local disk
through a provider five services instantiated themselves. On Vercel the
function's filesystem is read-only outside ``/tmp``, so the ``mkdir`` in
:meth:`LocalStorageProvider.save_file` raised ``OSError`` and the exception
escaped the route -- and Starlette mounts ``ServerErrorMiddleware`` *outside*
``CORSMiddleware``, so the answer was a bodiless 500 with no
``access-control-allow-origin``, which every browser reports as a CORS error.
Uploading a condominium logo in production failed for that reason, and so did
the obras report and the assembly minutes.

Two rules follow, and the module is arranged around them:

1. :func:`upload_storage_provider` and :func:`generated_storage_provider` are
   the **only** places a provider is built. With ``BLOB_READ_WRITE_TOKEN`` set
   they hand back a Vercel Blob provider for their own namespace; without it
   they hand back exactly the ``LocalStorageProvider`` -- same ``base_dir``,
   same ``url_prefix`` -- every caller used before, so local development and
   the test suite are unchanged.
2. **No storage failure escapes unhandled.** Every one of them, on every
   provider, becomes :class:`~app.core.exceptions.StorageUnavailableError`
   (503) or, for a content type that may not be stored at all,
   :class:`~app.core.exceptions.UnsupportedStorageContentTypeError` (422).
   ``delete_file`` keeps a best-effort contract on every provider: it returns
   ``bool`` and never raises, so a failed cleanup cannot fail a request.

A third rule arrived with the read side (APRAS-96). The Blob store used to be
**write-only**, so a Blob-stored logo could only ever be *linked* from the
obras report instead of embedded, on every render and for every tenant. Reading
an object back is a ``GET`` on the object URL itself, and it is bounded and
silent because its one caller is a public, uncached render:
:meth:`VercelBlobStorageProvider.read_file` reaches exactly one host -- the one
this deployment's own token names -- carries no credential, follows no
redirect, refuses a body past :data:`BLOB_MAX_READ_BYTES`, and **never raises**
for any input. Every failure is one ``logger.warning`` and a ``None``; a
success logs nothing.
"""

import abc
import logging
import os
import uuid
from pathlib import Path
from urllib.parse import urlencode, urlparse
from uuid import UUID

import httpx

from app.core import clock
from app.core.config import settings
from app.core.exceptions import (
    StorageUnavailableError,
    UnsupportedStorageContentTypeError,
)
from app.core.uploads import canonical_content_type, canonical_extension
from app.models.enums import StorageProvider

logger = logging.getLogger(__name__)


class BaseStorageProvider(abc.ABC):
    """Abstract interface for media asset storage providers."""

    #: Which backend actually holds the bytes. ``media_assets.storage_provider``
    #: records this rather than a hard-coded ``LOCAL_DISK``. The default is the
    #: disk because every in-tree test double inherits it and writes nowhere
    #: else; a provider that stores elsewhere overrides it.
    provider_kind: StorageProvider = StorageProvider.LOCAL_DISK

    @abc.abstractmethod
    def save_file(
        self,
        file_bytes: bytes,
        filename: str,
        content_type: str,
        *,
        tenant_id: UUID | None = None,
    ) -> tuple[str, str]:
        """
        Save file bytes to storage backend.

        ``tenant_id`` is the acting tenant, for namespacing an object path. It
        is an argument and not ambient state because the acting tenant is a
        session-level fact with no ``ContextVar`` to read it from, and it is
        **not** a security boundary: a provider is free to ignore it, as the
        local one does.

        Returns:
            Tuple[str, str]: (internal_file_path, public_or_relative_url)
        """

    @abc.abstractmethod
    def delete_file(self, file_path: str) -> bool:
        """
        Delete a stored file by its internal file path.

        Returns:
            bool: True if deleted successfully or missing, False otherwise.
        """

    def resolve_stored_path(self, url: str | None) -> str | None:
        """What this provider would delete to remove ``url``, or ``None``.

        The replacement for the ``/static/uploads/`` prefix check
        ``tenant_service`` and ``purchase_service`` each carried: that
        predicate silently skipped every Blob URL, orphaning the object it
        should have removed. ``None`` keeps APRAS-61's rule intact -- a URL
        this provider did not mint is somebody else's file and is left alone.

        The default is ``None``: a provider that cannot map a URL back to
        something it owns, which includes every stub and every test double,
        owns nothing.
        """
        del url
        return None

    def resolve_own_url(self, url: str | None) -> str | Path | None:
        """What this provider's **own** root holds behind ``url``.

        The read-side companion of :meth:`resolve_stored_path`, and the one
        place the "``/static/uploads/`` maps back to ``base_dir``" rule is
        stated. ``None`` means *this provider does not own that value*, which
        includes every stub and every test double. A local provider answers a
        ``Path``; a remote store answers the URL itself, because that *is*
        where its bytes are (APRAS-96).
        """
        del url
        return None

    def read_file(
        self, url: str | None, *, max_bytes: int | None = None
    ) -> bytes | None:
        """The bytes behind one of this provider's **own** URLs, or ``None``.

        A **concrete** default, deliberately: "this backend cannot read its own
        objects back". The three unimplemented provider stubs therefore stay
        untouched and no unimplemented-method exception can reach a client --
        the property ``tests/test_storage_blob.py`` holds by text scan over
        this module.

        ``max_bytes`` is keyword-only and defaulted, so APRAS-92 §B's ladder
        keeps calling ``read_file(url)`` with a single argument while a caller
        that owns a stricter limit can state it (APRAS-96).

        Never a network call on any provider that implements it against a
        remote store without saying so: the one caller
        (``TenantService.logo_data_uri``) runs inside an unauthenticated,
        uncached render.
        """
        del url, max_bytes
        return None


#: Where user-supplied uploads live, and the prefix the mount serving them
#: answers on. That mount forces a download for anything outside
#: ``INLINE_SAFE_EXTENSIONS``.
DEFAULT_UPLOAD_BASE_DIR = "static/uploads"
DEFAULT_UPLOAD_URL_PREFIX = "/static/uploads"

#: Where output **this application renders itself** lives, and its prefix. The
#: mount serving it renders inline, which is only safe because nothing a client
#: supplies is ever written here -- see :func:`generated_storage_provider`.
GENERATED_BASE_DIR = "static/generated"
GENERATED_URL_PREFIX = "/static/generated"

#: The first segment of a Blob object's pathname, one per tree. The same split
#: the two static mounts express, carried onto a store that has no mounts.
UPLOAD_NAMESPACE = "uploads"
GENERATED_NAMESPACE = "generated"

#: The pathname segment standing in for an acting tenant when a write happens
#: outside any tenant scope.
SHARED_NAMESPACE_SEGMENT = "shared"


class LocalStorageProvider(BaseStorageProvider):
    """Local disk storage provider saving to {base_dir}/{year}/{month}/."""

    provider_kind = StorageProvider.LOCAL_DISK

    def __init__(
        self,
        base_dir: str | Path = DEFAULT_UPLOAD_BASE_DIR,
        url_prefix: str = DEFAULT_UPLOAD_URL_PREFIX,
    ) -> None:
        """``url_prefix`` is paired with ``base_dir``: it is what the mount
        serving that directory answers on, and both default to the upload
        tree so every existing caller mints exactly the URL it minted before.
        """
        self.base_dir = Path(base_dir)
        self.url_prefix = url_prefix.rstrip("/")

    def save_file(
        self,
        file_bytes: bytes,
        filename: str,
        content_type: str,
        *,
        tenant_id: UUID | None = None,
    ) -> tuple[str, str]:
        """Write the bytes under a UUID name whose suffix comes from the type.

        ``filename`` is **display metadata and nothing else**: it does not
        reach the disk. The suffix is derived from the already-validated
        ``content_type`` instead, because the static mount guesses what it
        serves from the extension and the client must not get to choose it
        (APRAS-65). An unmapped type yields an inert ``.bin``.

        ``tenant_id`` is ignored: this tree's layout is ``{year}/{month}``, and
        namespacing by tenant is a property of the Blob pathname alone. Both
        unused arguments are dropped with ``del`` rather than two ``noqa``
        directives, whose count ``tests/test_lint_hygiene.py`` caps.
        """
        del filename, tenant_id

        now = clock.db_now()
        year_month_subfolder = f"{now.year}/{now.month:02d}"
        target_dir = self.base_dir / year_month_subfolder
        try:
            target_dir.mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            # The belt to the braces (APRAS-94 §6): with no Blob token
            # configured, a serverless deploy lands here, and it must answer
            # with a diagnosable body instead of crashing the route.
            raise StorageUnavailableError(
                "o sistema de arquivos é somente leitura (read-only file "
                "system) e nenhum armazenamento remoto está configurado; "
                "defina BLOB_READ_WRITE_TOKEN"
            ) from exc

        unique_name = f"{uuid.uuid4()}{canonical_extension(content_type)}"
        relative_path = os.path.join(year_month_subfolder, unique_name)
        full_path = target_dir / unique_name

        try:
            with open(full_path, "wb") as f:
                f.write(file_bytes)
        except OSError as exc:
            raise StorageUnavailableError(
                f"falha ao gravar em disco: {exc.strerror or exc}"
            ) from exc

        url = f"{self.url_prefix}/{relative_path}"
        return str(full_path), url

    def delete_file(self, file_path: str) -> bool:
        try:
            path = Path(file_path)
            if path.exists():
                path.unlink()
            return True
        except Exception:  # noqa: BLE001  # best-effort side effect; a failure here must not fail the request
            return False

    def resolve_stored_path(self, url: str | None) -> str | None:
        """Map one of **this instance's own** URLs back to a path on disk.

        Keyed off ``self.url_prefix`` and never off a module-level
        ``/static/uploads`` literal, so the ``static/generated`` instance
        resolves its own values too. The path is built relative to
        ``base_dir`` rather than by stripping the leading slash: identical for
        the production provider and honest for any other one.
        """
        prefix = f"{self.url_prefix}/"
        if url is None or not url.startswith(prefix):
            return None
        return str(self.base_dir / url[len(prefix) :])

    def resolve_own_url(self, url: str | None) -> Path | None:
        """:meth:`resolve_stored_path`, plus a containment check (APRAS-92 §B).

        The prefix rule is not restated: it is asked of
        :meth:`resolve_stored_path`, so "what this provider owns" has one
        definition for reads and for deletes alike.

        What is added is the check the delete path never had. A stored
        ``logo_url`` is **data**, and a read primitive invoked from a public,
        unauthenticated route must not depend on who wrote it: the joined path
        is resolved and refused unless it is still inside ``base_dir``, so
        ``/static/uploads/../../../etc/passwd`` maps to nothing. Not reachable
        today -- the only writer is the validated upload path -- which is
        exactly why it is cheap defence in depth rather than a fix.
        """
        stored = self.resolve_stored_path(url)
        if stored is None:
            return None
        root = self.base_dir.resolve()
        candidate = Path(stored).resolve()
        if not candidate.is_relative_to(root):
            return None
        return candidate

    def read_file(
        self, url: str | None, *, max_bytes: int | None = None
    ) -> bytes | None:
        """The bytes of one of this provider's own files, or ``None``.

        ``None`` for a value this provider does not own, for one that escapes
        its root, and for a file that is missing or unreadable: a caller
        embedding a logo degrades, it does not fail.

        ``max_bytes`` carries the same meaning it does on the base and on the
        Blob provider, and it is honoured rather than merely accepted: a caller
        that states a limit is told the truth about it. Accepting the keyword
        and ignoring it would be worse than not accepting it.

        **No implicit ceiling.** When ``max_bytes`` is ``None`` the whole file
        is read, exactly as before this keyword existed. Imposing the Blob
        provider's 2 MiB default here would give local disk a bound it never
        had, and the size of an uploaded logo is already enforced one frame up
        by ``TenantService.set_logo``.

        The keyword exists here because the base declares it (APRAS-96). An
        override narrower than the base is a trap nothing in this project would
        catch -- there is no mypy and no pyright in CI -- so it would surface as
        a ``TypeError`` at the one call site that ever passes a limit, on
        whichever deployment happens to be configured for local disk.
        """
        path = self.resolve_own_url(url)
        if path is None:
            return None
        try:
            if max_bytes is None:
                return path.read_bytes()
            # One read of ceiling + 1 rather than `stat()` then `read_bytes()`:
            # it is a syscall fewer, it has no window between the check and the
            # read, and the bound then applies to what was actually read rather
            # than to what the directory entry claimed.
            with path.open("rb") as handle:
                payload = handle.read(max_bytes + 1)
        except OSError:
            return None
        if len(payload) > max_bytes:
            logger.warning(
                "Disco local: leitura recusada, o arquivo excede o limite "
                "pedido (arquivo=%s, limite=%d)",
                path.name,
                max_bytes,
            )
            return None
        return payload


#: Vercel's Blob REST API, as read out of ``@vercel/blob`` 2.6.1's own compiled
#: client in ``repertoire_hero/node_modules/@vercel/blob/dist`` (``getApiUrl``,
#: ``requestApi``, ``createPutHeaders``, ``del``) rather than out of prose
#: documentation. There is no published REST reference, so the version is
#: pinned and named: **a 4xx naming the API version is the signal to bump this
#: constant**, and the mapped error carries the API's own code and message so
#: that signal is observable in production rather than guessed at.
BLOB_API_BASE_URL = "https://vercel.com/api/blob"
BLOB_API_VERSION = "12"

#: The host every public Blob object is served from. Used to decide whether a
#: stored value is one of ours (:meth:`BaseStorageProvider.resolve_stored_path`).
BLOB_HOST_SUFFIX = ".blob.vercel-storage.com"

#: Where the store id sits in a ``vercel_blob_rw_<storeId>_<random>`` token,
#: reading it exactly as the SDK's ``parseStoreIdFromReadWriteToken`` does.
BLOB_TOKEN_STORE_ID_FIELD = 3

#: Explicitly bounded on every phase: an unbounded default read timeout would
#: hold a serverless invocation (and, locally, the event loop) for as long as
#: the API takes to answer.
BLOB_TIMEOUT = httpx.Timeout(connect=5.0, read=30.0, write=30.0, pool=5.0)

#: The most bytes :meth:`VercelBlobStorageProvider.read_file` will buffer when
#: the caller states no limit of its own. Exactly
#: ``TenantService.LOGO_MAX_FILE_SIZE``, so **no logo the product ever accepted
#: is refused by the default**. The consequence is the one APRAS-92 §B records:
#: base64 inflates by 4/3, so a worst-case embed adds roughly 2.7 MiB to a
#: render of an uncached public route. This provider does not own that policy --
#: it owns a safe default and the honouring of a caller's tighter one.
BLOB_MAX_READ_BYTES = 2 * 1024 * 1024

#: The most bytes of a refused Blob response body a single log record carries
#: (APRAS-101). Comfortably holds a Blob API error JSON and stops an
#: intermediary's HTML error page from being copied into Vercel's durable log
#: stream. The bound is applied **after** the credential scrub, never before --
#: see :meth:`VercelBlobStorageProvider._refusal_body`.
BLOB_LOG_BODY_MAX_BYTES = 512

#: Appended when the body was longer than the bound, so a truncated record can
#: never be read as a complete one.
BLOB_LOG_TRUNCATION_MARKER = " \u2026(truncado)"

#: The *response* headers a refusal record may carry, each only when present.
#: All five are diagnostic -- the error-code and ``retry-after`` pair is what
#: identifies a ``400`` produced by an intermediary rather than by the Blob API
#: -- and none of them can hold a credential of ours. The **request** headers
#: are never logged: :meth:`VercelBlobStorageProvider._auth_headers` puts the
#: store's read-write token in ``authorization``.
BLOB_LOG_RESPONSE_HEADERS = (
    "x-vercel-error",
    "x-vercel-error-code",
    "x-vercel-id",
    "content-type",
    "retry-after",
)

#: ``{storeId}.{access}.blob.vercel-storage.com`` is five labels, and the count
#: is part of the read predicate: without it,
#: ``{store}.public.a.blob.vercel-storage.com`` would pass. Named because a
#: bare ``5`` is a magic value.
BLOB_HOST_LABEL_COUNT = 5


class VercelBlobStorageProvider(BaseStorageProvider):
    """Vercel Blob storage over its REST API, with no new dependency.

    ``httpx`` is already a dependency and the REST contract suffices, so the
    ``@vercel/blob`` SDK (a Node package) is not needed. The client is the
    **synchronous** one: every ``save_file`` caller is a synchronous service
    function, and a function running on the event loop thread cannot await an
    offload. That blocks the loop for the duration of an upload -- accepted
    deliberately (APRAS-94, "The blocking call"): these routes already run
    synchronous SQLAlchemy work inline, a Vercel invocation serves one request,
    and the timeout above bounds the worst case. The cheap upgrade, if local
    latency ever matters, is ``run_in_threadpool`` at the *route* boundary,
    which needs no change here.
    """

    provider_kind = StorageProvider.VERCEL_BLOB

    def __init__(
        self,
        *,
        namespace: str,
        token: str | None,
        allow_html: bool = False,
    ) -> None:
        """``allow_html`` is the two static mounts' split, carried onto Blob.

        Only the instance :func:`generated_storage_provider` returns accepts
        ``text/html``, because only server-rendered output is written there.
        The instance :func:`upload_storage_provider` returns refuses it, which
        is what the uploads mount's forced download does today.
        """
        self.namespace = namespace
        self.token = token
        self.allow_html = allow_html

    # -- the contract ------------------------------------------------------

    def save_file(
        self,
        file_bytes: bytes,
        filename: str,
        content_type: str,
        *,
        tenant_id: UUID | None = None,
    ) -> tuple[str, str]:
        """``PUT`` the bytes under a freshly minted UUID pathname.

        ``filename`` is unused for exactly the reason it is unused on disk: it
        is display metadata, and the stored suffix comes from the validated
        ``content_type`` (APRAS-65). Dropped with ``del`` rather than a
        ``noqa``, whose count ``tests/test_lint_hygiene.py`` caps.

        Both return values are the blob URL: callers that persisted
        ``file_path`` (finance, announcements, media) delete through the same
        value as callers that persisted the URL.
        """
        del filename

        stored_type = self._assert_storable(content_type)
        store_id = self._store_id()
        pathname = self._pathname(stored_type, tenant_id)

        request_url = f"{BLOB_API_BASE_URL}/?{urlencode({'pathname': pathname})}"
        response = self._request(
            "PUT",
            request_url,
            headers={
                **self._auth_headers(store_id),
                "x-vercel-blob-access": "public",
                "x-content-type": stored_type,
                # The object name is already a UUID, so there is nothing to
                # disambiguate. `x-allow-overwrite` is deliberately **not**
                # sent: an overwrite cannot legitimately occur, so a collision
                # must stay an error rather than silently replace an object.
                "x-add-random-suffix": "0",
            },
            content=file_bytes,
        )
        if not response.is_success:
            # Emitted **before** `_describe`, deliberately: the diagnostic must
            # not depend on `_describe` (nor on the `_payload` parse inside it)
            # staying non-raising for every body shape the API can answer.
            self._log_refusal("PUT", request_url, response)
            raise StorageUnavailableError(self._describe(response))

        url = self._url_of(response, request_url)
        return url, url

    def delete_file(self, file_path: str) -> bool:
        """Best-effort removal. Never raises, and never guesses.

        A value :meth:`resolve_stored_path` rejects -- a filesystem path
        written before the token was configured, an externally hosted URL --
        makes **no HTTP call at all**: it is not this store's object, so
        POSTing it to the delete endpoint could only ever be noise.
        """
        if self.resolve_stored_path(file_path) is None:
            return False
        delete_url = f"{BLOB_API_BASE_URL}/delete"
        try:
            response = self._request(
                "POST",
                delete_url,
                headers={
                    **self._auth_headers(self._store_id()),
                    "content-type": "application/json",
                },
                json={"urls": [file_path]},
            )
        except StorageUnavailableError:
            return False
        if not response.is_success:
            # Silent before APRAS-101: the `False` was swallowed by every
            # caller, so a store that refuses deletes left no trace at all.
            self._log_refusal("POST", delete_url, response)
            return False
        return True

    def resolve_stored_path(self, url: str | None) -> str | None:
        """The URL itself when it is a Blob object's, else ``None``."""
        if not url:
            return None
        host = urlparse(url).hostname or ""
        return url if host.endswith(BLOB_HOST_SUFFIX) else None

    # -- the read side (APRAS-96) ------------------------------------------

    def resolve_own_url(self, url: str | None) -> str | None:
        """The URL itself when **this** store minted it, else ``None``.

        A separate and strictly tighter predicate than
        :meth:`resolve_stored_path`, which tests the host *suffix* alone.
        Suffix-only is sufficient for a delete: that request goes to
        :data:`BLOB_API_BASE_URL` with our own token, so a foreign URL yields
        at worst a failed delete against our own store and never an outbound
        request to a host somebody else named. It is **not** sufficient for a
        read reachable from a public, unauthenticated route, because every
        Vercel Blob customer's store shares ``.blob.vercel-storage.com``.

        So the host is taken apart label by label and all four clauses must
        hold: five labels; the first is this deployment's own store id; the
        second is the access label; the last three are exactly the suffix.
        Each looser phrasing admits something it should not -- "store id plus
        the suffix" is literally false for the real host, and dropping the
        count or the access label admits
        ``{store}.evil.blob.vercel-storage.com`` and
        ``{store}.a.b.blob.vercel-storage.com``. Together they make the set of
        reachable hosts a *single name per access value*, fixed by our own
        token: not a suffix and not an allowlist.

        Performs no I/O of any kind and never raises. A token that yields no
        store id becomes ``None`` rather than an error: with nothing to
        identify the store, there is nothing for it to own.
        """
        if not url:
            return None
        try:
            parsed = urlparse(url)
            port = parsed.port
        except ValueError:
            # An unparseable authority -- a malformed IPv6 literal, a port that
            # is not a number. `urlparse` raises on the first and only on the
            # field read for the second, and either read *is* the validation.
            return None
        if (
            parsed.scheme != "https"
            or port is not None
            or parsed.username
            or parsed.password
        ):
            return None
        try:
            store_id = self._store_id()
        except StorageUnavailableError:
            return None
        labels = (parsed.hostname or "").split(".")
        owned = (
            len(labels) == BLOB_HOST_LABEL_COUNT
            and labels[0] == store_id.casefold()
            and labels[1] in {"public", "private"}
            and "." + ".".join(labels[2:]) == BLOB_HOST_SUFFIX
        )
        return url if owned else None

    def read_file(
        self, url: str | None, *, max_bytes: int | None = None
    ) -> bytes | None:
        """The object's bytes, or ``None``. **Never raises, for any input.**

        The promise matters because the only caller is APRAS-92's obras report,
        rendered on a public route: an escaping exception would reach
        ``ServerErrorMiddleware``, which sits outside ``CORSMiddleware``, and
        reproduce the bodiless, header-less 500 APRAS-94 §6 exists to prevent.
        A report that cannot read a logo renders without one.

        Every failure shape therefore collapses to the same ``None``, preceded
        by exactly one ``logger.warning`` naming the reason -- a ``None`` no one
        can diagnose is worse than a linked logo -- and the success path logs
        nothing, because one line per render of an uncached route is noise. The
        catch names the two shapes that are expected and is then closed by a
        best-effort ``except Exception``: "never raises" is promised to an
        anonymous route and must not depend on having enumerated everything
        ``httpx`` can produce.
        """
        ceiling = BLOB_MAX_READ_BYTES if max_bytes is None else max_bytes
        try:
            own_url = self.resolve_own_url(url)
            if own_url is None:
                logger.warning(
                    "Vercel Blob: leitura recusada, a URL não é um objeto "
                    "deste store (host=%s)",
                    self._host_of(url),
                )
                return None
            return self._read_object(own_url, ceiling)
        except (StorageUnavailableError, httpx.HTTPError) as exc:
            logger.warning(
                "Vercel Blob: falha ao ler o objeto (host=%s): %s",
                self._host_of(url),
                exc,
            )
            return None
        except Exception:  # noqa: BLE001  # a public, uncached render must never see an exception from here, and the promise cannot depend on enumerating every error httpx can raise
            logger.warning(
                "Vercel Blob: erro inesperado ao ler o objeto (host=%s)",
                self._host_of(url),
            )
            return None

    def _read_object(self, url: str, ceiling: int) -> bytes | None:
        """The one outbound request, streamed and credential-free."""
        # `follow_redirects=False` is also httpx's default, stated here so it
        # reads as a decision: a `3xx` is not a success status, so it takes the
        # ordinary non-2xx path and the server never issues the second request.
        #
        # No `authorization` header either. Everything this provider writes is
        # `public`-access and needs no credential to be read, and a request that
        # carries none cannot leak the write token even if the host check were
        # ever wrong.
        with (
            httpx.Client(timeout=BLOB_TIMEOUT, follow_redirects=False) as client,
            client.stream("GET", url) as response,
        ):
            return self._collect(response, url, ceiling)

    def _collect(
        self, response: httpx.Response, url: str, ceiling: int
    ) -> bytes | None:
        """The bound, enforced twice, because either alone is insufficient.

        ``Content-Length`` is checked before a single body byte is read, and
        the stream is then abandoned the moment the accumulated length passes
        the ceiling. The second check is the one that actually holds: the
        header is absent on a chunked response, it is a claim by the remote
        either way, and it counts *encoded* bytes while ``iter_bytes()`` yields
        decoded ones -- so on a ``content-encoding: gzip`` response only the
        streamed check bounds what is buffered.
        """
        host = self._host_of(url)
        if not response.is_success:
            logger.warning(
                "Vercel Blob: a leitura respondeu %s (host=%s)",
                response.status_code,
                host,
            )
            return None
        declared = response.headers.get("content-length")
        if declared is not None and declared.isdigit() and int(declared) > ceiling:
            logger.warning(
                "Vercel Blob: o objeto declara %s bytes, acima do limite de "
                "%s (host=%s)",
                declared,
                ceiling,
                host,
            )
            return None
        buffer = bytearray()
        for chunk in response.iter_bytes():
            buffer.extend(chunk)
            if len(buffer) > ceiling:
                logger.warning(
                    "Vercel Blob: leitura abandonada ao passar de %s bytes (host=%s)",
                    ceiling,
                    host,
                )
                return None
        if not buffer:
            logger.warning("Vercel Blob: o objeto lido está vazio (host=%s)", host)
            return None
        return bytes(buffer)

    @staticmethod
    def _host_of(url: str | None) -> str:
        """The host alone, for a log line.

        Never the token and never the URL's query string, which a Blob URL may
        legitimately carry.

        The guard covers three types, not one. This runs **inside**
        ``read_file``'s exception handlers, building the message for a failure
        that has already happened, so anything it raises escapes the very
        promise those handlers exist to keep -- ``read_file`` never raises, for
        any input. ``urlparse`` answers ``ValueError`` on a malformed authority,
        and ``AttributeError`` or ``TypeError`` on a value that is not a string
        at all; the column this reads is a database string today only by
        convention, and a ``Path`` or an ``int`` reaching here would otherwise
        turn a logged failure into an unlogged one.

        Named rather than blanket on purpose: a bare ``except Exception`` would
        spend one of the module's counted ``noqa`` allowances to catch nothing
        these three do not already cover.
        """
        try:
            return urlparse(url or "").hostname or "-"
        except (ValueError, AttributeError, TypeError):
            return "-"

    # -- the request -------------------------------------------------------

    def _store_id(self) -> str:
        """The fourth ``_``-separated field of the read-write token.

        Exactly what the SDK's ``parseStoreIdFromReadWriteToken`` reads out of
        ``vercel_blob_rw_<storeId>_<random>``. A token that does not yield one
        is a configuration fault, diagnosed at the point of use and named so an
        operator knows which variable to fix.
        """
        token = self.token or ""
        # A header value httpx cannot encode raises `UnicodeEncodeError` from
        # deep inside the transport -- outside the `httpx.HTTPError` family
        # `_request` maps, so it would escape unhandled and reproduce the very
        # bodiless, CORS-header-less 500 this provider exists to remove. A
        # pasted smart quote in the Vercel dashboard is enough. Refuse here,
        # where the fault is named, rather than at the socket.
        if not token.isascii():
            raise StorageUnavailableError(
                "BLOB_READ_WRITE_TOKEN contém caracteres não-ASCII; "
                "reconfigure a variável de ambiente BLOB_READ_WRITE_TOKEN "
                "copiando o valor exato do painel do Vercel Blob"
            )
        fields = token.split("_")
        store_id = (
            fields[BLOB_TOKEN_STORE_ID_FIELD]
            if len(fields) > BLOB_TOKEN_STORE_ID_FIELD
            else ""
        )
        if not store_id:
            raise StorageUnavailableError(
                "BLOB_READ_WRITE_TOKEN ausente ou malformado; configure a "
                "variável de ambiente BLOB_READ_WRITE_TOKEN do Vercel Blob"
            )
        return store_id

    def _auth_headers(self, store_id: str) -> dict[str, str]:
        return {
            "authorization": f"Bearer {self.token}",
            "x-api-version": BLOB_API_VERSION,
            "x-vercel-blob-store-id": store_id,
        }

    def _assert_storable(self, content_type: str) -> str:
        """The canonical type to store as, or a 422.

        A Blob object is served by Vercel's CDN and never passes through
        ``HardenedStaticFiles``, so the mount's forced download for unsafe
        extensions is unavailable. What replaces it is refusing anything
        ``app.core.uploads`` does not name, plus ``text/html`` outside the
        generated namespace. Stricter than the disk's inert ``.bin``, and
        unreachable from any endpoint: every service allowlist is a subset of
        ``CONTENT_TYPE_EXTENSIONS`` (``tests/test_upload_filename_safety.py``).
        """
        stored_type = canonical_content_type(content_type)
        if stored_type is None or (stored_type == "text/html" and not self.allow_html):
            raise UnsupportedStorageContentTypeError(content_type)
        return stored_type

    def _pathname(self, stored_type: str, tenant_id: UUID | None) -> str:
        """``{namespace}/{tenant or shared}/{year}/{month}/{uuid}{ext}``.

        The tenant segment is operational -- offboarding, attribution,
        debugging -- and not a security boundary: public Blob URLs are
        unguessable either way.
        """
        now = clock.db_now()
        tenant_segment = (
            str(tenant_id) if tenant_id is not None else SHARED_NAMESPACE_SEGMENT
        )
        name = f"{uuid.uuid4()}{canonical_extension(stored_type)}"
        return f"{self.namespace}/{tenant_segment}/{now.year}/{now.month:02d}/{name}"

    def _request(self, method: str, url: str, **kwargs) -> httpx.Response:
        try:
            with httpx.Client(timeout=BLOB_TIMEOUT) as client:
                return client.request(method, url, **kwargs)
        except httpx.HTTPError as exc:
            raise StorageUnavailableError(
                f"falha de comunicação com o Vercel Blob: {exc}"
            ) from exc

    # -- the response ------------------------------------------------------

    @staticmethod
    def _payload(response: httpx.Response) -> object | None:
        """The parsed body, or ``None`` when it is not JSON.

        Nothing subscripts a ``json()`` result before it has been validated: a
        response-shape change on a 2xx would otherwise raise
        ``JSONDecodeError``/``KeyError`` out of ``save_file`` and reproduce the
        bodiless, header-less 500 this whole task exists to eliminate.
        """
        try:
            return response.json()
        except ValueError:
            return None

    @classmethod
    def _describe(cls, response: httpx.Response) -> str:
        """The status, plus the API's own ``error.code``/``error.message``.

        Carried into the raised message whenever the body supplies them, so "a
        4xx naming the API version is the signal to bump the constant" is an
        observable production signal and not a guess.
        """
        detail = ""
        payload = cls._payload(response)
        if isinstance(payload, dict):
            error = payload.get("error")
            if isinstance(error, dict):
                parts = [
                    str(error[key]) for key in ("code", "message") if error.get(key)
                ]
                detail = f" ({': '.join(parts)})" if parts else ""
        return f"o Vercel Blob respondeu {response.status_code}{detail}"

    def _url_of(self, response: httpx.Response, request_url: str) -> str:
        """The ``url`` of a successful response, validated before it is used.

        An instance method since APRAS-101, and taking the request URL: the
        refusal record it now emits needs both the configured token (to scrub
        it out of the body) and the URL that was asked for. The method it
        records is the literal ``"PUT"`` because ``save_file``'s upload is its
        only caller -- a 2xx with no usable ``url`` can arrive from nowhere
        else.
        """
        payload = self._payload(response)
        url = payload.get("url") if isinstance(payload, dict) else None
        if not isinstance(url, str) or not url:
            self._log_refusal("PUT", request_url, response)
            raise StorageUnavailableError(
                "o Vercel Blob respondeu "
                f"{response.status_code} sem uma URL utilizável; o contrato da "
                f"API (x-api-version {BLOB_API_VERSION}) pode ter mudado"
            )
        return url

    # -- why a refusal happened (APRAS-101) --------------------------------

    def _log_refusal(self, method: str, url: str, response: httpx.Response) -> None:
        """One WARNING per Blob response this provider cannot use.

        ``_describe`` reads the body only when it is JSON shaped exactly
        ``{"error": {"code", "message"}}``, and nothing logged anything, so
        every other shape -- a bare ``{"message": ...}``, a plain-text line, an
        intermediary's HTML page -- reached production as a bare status code.
        This is the record that turns it into a sentence.

        Diagnostic only: nothing a caller observes is derived from it. The raw
        body is never promoted into the client-visible error, which also keeps
        Vercel's own error text out of a browser response.
        """
        logger.warning(
            "Vercel Blob: resposta inutilizável para %s %s: "
            "status=%s, cabeçalhos=%s, corpo=%s",
            method,
            url,
            response.status_code,
            self._refusal_headers(response),
            self._refusal_body(response),
        )

    def _refusal_headers(self, response: httpx.Response) -> dict[str, str]:
        """The allowlisted response headers that are actually present.

        A dict, so an absent header leaves no placeholder behind. Scrubbed all
        the same: an API that echoed a request header back would otherwise put
        the credential in the record.
        """
        present = {}
        for name in BLOB_LOG_RESPONSE_HEADERS:
            value = response.headers.get(name)
            if value is not None:
                present[name] = self._scrubbed_text(value)
        return present

    def _refusal_body(self, response: httpx.Response) -> str:
        """The body, scrubbed over its **whole** length and only then bounded.

        The order is a security property, not a preference. Truncating first
        can cut an echoed token mid-string: the surviving prefix no longer
        matches the full-token pattern, so it passes the scrub untouched and a
        usable part of the store's read-write credential reaches Vercel's
        durable log stream, where it stays permanently.

        The bound is a byte slice over the scrubbed *bytes* rather than over
        ``response.text``, so it is exact whatever the encoding, and the slice
        is decoded with ``errors="replace"`` because it may land mid-character.
        """
        scrubbed = self._scrubbed_bytes(response.content)
        if len(scrubbed) <= BLOB_LOG_BODY_MAX_BYTES:
            return scrubbed.decode("utf-8", errors="replace")
        kept = scrubbed[:BLOB_LOG_BODY_MAX_BYTES].decode("utf-8", errors="replace")
        return kept + BLOB_LOG_TRUNCATION_MARKER

    def _scrubbed_bytes(self, raw: bytes) -> bytes:
        """``raw`` with every occurrence of the configured token replaced."""
        token = self.token or ""
        if not token:
            return raw
        return raw.replace(token.encode("utf-8", errors="replace"), b"***")

    def _scrubbed_text(self, text: str) -> str:
        """``text`` with every occurrence of the configured token replaced."""
        return text.replace(self.token, "***") if self.token else text


def upload_storage_provider() -> BaseStorageProvider:
    """The provider every **client-supplied** upload is written through.

    One of exactly two decision points, and the reason no service names a
    provider class any more: five modules used to bind
    ``LocalStorageProvider()`` themselves, so making uploads work on a
    read-only filesystem would have meant five edits and five chances to miss
    one. With no token configured this returns byte-for-byte today's provider,
    which is what keeps local development and the whole suite unchanged.
    """
    if settings.BLOB_READ_WRITE_TOKEN:
        return VercelBlobStorageProvider(
            namespace=UPLOAD_NAMESPACE, token=settings.BLOB_READ_WRITE_TOKEN
        )
    return LocalStorageProvider(
        base_dir=DEFAULT_UPLOAD_BASE_DIR, url_prefix=DEFAULT_UPLOAD_URL_PREFIX
    )


def generated_storage_provider() -> BaseStorageProvider:
    """The provider the assembly-minutes and works-report generators use.

    Server-rendered HTML has to be served inline to be of any use, and the
    upload mount refuses to do that for a good reason. So generated output
    gets its own tree and its own mount. This factory is the **only** way any
    service reaches that tree: no call site names the directory itself, so
    "what can land next to inline-rendered HTML" stays answerable by reading
    this one function's callers -- and on Blob, where there is no mount at all,
    ``allow_html`` is what carries that same split.
    """
    if settings.BLOB_READ_WRITE_TOKEN:
        return VercelBlobStorageProvider(
            namespace=GENERATED_NAMESPACE,
            token=settings.BLOB_READ_WRITE_TOKEN,
            allow_html=True,
        )
    return LocalStorageProvider(
        base_dir=GENERATED_BASE_DIR, url_prefix=GENERATED_URL_PREFIX
    )


class _UnconfiguredStorageProvider(BaseStorageProvider):
    """A backend this deployment has no implementation for.

    The two stubs below used to raise a bare not-implemented builtin from both
    methods, which is an unhandled exception: it escapes the route, bypasses
    ``CORSMiddleware`` and produces the bodiless 500 that started this task.
    Both raise the mapped 503 instead (APRAS-94 §6) -- the best-effort
    ``delete_file`` contract belongs to the two providers that can actually
    store something, and a stub reporting a clean ``False`` would claim a
    cleanup it never attempted.
    """

    #: Named in the error, so the body says which backend is missing.
    backend_name = "desconhecido"

    def save_file(
        self,
        file_bytes: bytes,
        filename: str,
        content_type: str,
        *,
        tenant_id: UUID | None = None,
    ) -> tuple[str, str]:
        del file_bytes, filename, content_type, tenant_id
        raise self._unavailable()

    def delete_file(self, file_path: str) -> bool:
        del file_path
        raise self._unavailable()

    def _unavailable(self) -> StorageUnavailableError:
        return StorageUnavailableError(
            f"o provedor {self.backend_name} não está implementado nesta instalação"
        )


class S3StorageProvider(_UnconfiguredStorageProvider):
    """Unimplemented AWS S3 storage provider (out of scope for APRAS-94)."""

    provider_kind = StorageProvider.AWS_S3
    backend_name = "AWS S3"


class CloudinaryStorageProvider(_UnconfiguredStorageProvider):
    """Unimplemented Cloudinary storage provider (out of scope for APRAS-94)."""

    provider_kind = StorageProvider.CLOUDINARY
    backend_name = "Cloudinary"
