"""many_to_many_user_types_and_task_visibility

Revision ID: 3f75bcd3d49f
Revises: 0003
Create Date: 2026-08-10 08:51:32.445645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3f75bcd3d49f'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_user_type_link',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('user_type_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_type.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'user_type_id')
    )
    op.drop_constraint(op.f('category_name_key'), 'category', type_='unique')
    op.add_column('task', sa.Column('visible_to_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_task_visible_to_id'), 'task', ['visible_to_id'], unique=False)
    op.create_foreign_key(None, 'task', 'user_type', ['visible_to_id'], ['id'])

    # Migrate existing task visibility: set visible_to_id to 'Gerente Operacional' type ID for manager_visible tasks
    op.execute("UPDATE task SET visible_to_id = (SELECT id FROM user_type WHERE name = 'Gerente Operacional' LIMIT 1) WHERE manager_visible = true")

    # Migrate existing user types: insert links into user_user_type_link from user.type_id
    op.execute("INSERT INTO user_user_type_link (user_id, user_type_id) SELECT id, type_id FROM \"user\" WHERE type_id IS NOT NULL")

    op.drop_column('task', 'manager_visible')
    op.drop_index(op.f('ix_user_type_id'), table_name='user')
    op.drop_constraint(op.f('fk_user_type_id'), 'user', type_='foreignkey')
    op.drop_column('user', 'type_id')
    op.drop_constraint(op.f('user_type_name_key'), 'user_type', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_type_name_key'), 'user_type', ['name'], postgresql_nulls_not_distinct=False)
    op.add_column('user', sa.Column('type_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_user_type_id'), 'user', 'user_type', ['type_id'], ['id'])
    op.create_index(op.f('ix_user_type_id'), 'user', ['type_id'], unique=False)
    op.add_column('task', sa.Column('manager_visible', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))

    # Migrate data back: populate type_id from user_user_type_link
    op.execute("UPDATE \"user\" SET type_id = (SELECT user_type_id FROM user_user_type_link WHERE user_id = \"user\".id LIMIT 1)")

    # Migrate task visibility back: set manager_visible = true for tasks with target user types
    op.execute("UPDATE task SET manager_visible = true WHERE visible_to_id IS NOT NULL")

    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_index(op.f('ix_task_visible_to_id'), table_name='task')
    op.drop_column('task', 'visible_to_id')
    op.create_unique_constraint(op.f('category_name_key'), 'category', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_table('user_user_type_link')
    # ### end Alembic commands ###
